# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `aws-partitions` gem.
# Please instead update this file by running `bin/tapioca gem aws-partitions`.


# source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#3
module Aws
  class << self
    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#93
    def config; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#96
    def config=(config); end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#155
    def eager_autoload!(*args); end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#148
    def empty_connection_pools!; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#105
    def partition(partition_name); end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#110
    def partitions; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#86
    def shared_config; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#125
    def use_bundled_cert!; end
  end
end

# source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#4
module Aws::Partitions
  extend ::Enumerable

  class << self
    # source://aws-partitions//lib/aws-partitions.rb#192
    def add(new_partitions); end

    # source://aws-partitions//lib/aws-partitions.rb#206
    def clear; end

    # source://aws-partitions//lib/aws-partitions.rb#233
    def default_metadata; end

    # source://aws-partitions//lib/aws-partitions.rb#213
    def default_partition_list; end

    # source://aws-partitions//lib/aws-partitions.rb#223
    def defaults; end

    # source://aws-partitions//lib/aws-partitions.rb#137
    def each(&block); end

    # source://aws-partitions//lib/aws-partitions.rb#201
    def merge_metadata(partition_metadata); end

    # source://aws-partitions//lib/aws-partitions.rb#164
    def partition(name); end

    # source://aws-partitions//lib/aws-partitions.rb#186
    def partitions; end

    # source://aws-partitions//lib/aws-partitions.rb#244
    def service_ids; end
  end
end

# source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#6
class Aws::Partitions::EndpointProvider
  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#31
  def initialize(rules); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#73
  def dns_suffix_for(region, service, variants); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#46
  def resolve(region, service, sts_regional_endpoints, variants); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#51
  def signing_region(region, service, sts_regional_endpoints); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#57
  def signing_service(region, service); end

  private

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#178
  def build_is_global_fn(sts_regional_endpoints = T.unsafe(nil)); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#83
  def configured_variants?(variants); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#192
  def credential_scope(region, service, is_global_fn); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#238
  def default_partition; end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#125
  def endpoint_for(region, service, is_global_fn, variants); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#141
  def endpoint_no_variants_for(region, service, is_global_fn); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#133
  def endpoint_with_variants_for(region, service, variants); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#87
  def fetch_variant(cfg, tags); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#212
  def get_partition(region_or_partition); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#219
  def partition_containing_region(region); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#234
  def partition_matching_name(partition_name); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#225
  def partition_matching_region(region); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#92
  def resolve_variant(region, service, config_variants); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#117
  def validate_variant!(config_variants, resolved_variant); end

  # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#171
  def warn_deprecation(service, region); end

  class << self
    # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#256
    def dns_suffix_for(region, service = T.unsafe(nil), variants = T.unsafe(nil)); end

    # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#244
    def resolve(region, service, sts_endpoint = T.unsafe(nil), variants = T.unsafe(nil)); end

    # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#248
    def signing_region(region, service, sts_regional_endpoints = T.unsafe(nil)); end

    # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#252
    def signing_service(region, service); end

    private

    # source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#262
    def default_provider; end
  end
end

# source://aws-partitions//lib/aws-partitions/endpoint_provider.rb#9
Aws::Partitions::EndpointProvider::STS_LEGACY_REGIONS = T.let(T.unsafe(nil), Array)

# source://aws-partitions//lib/aws-partitions/metadata.rb#6
module Aws::Partitions::Metadata
  class << self
    # source://aws-partitions//lib/aws-partitions/metadata.rb#25
    def default_partition_metadata; end

    # source://aws-partitions//lib/aws-partitions/metadata.rb#10
    def partition(region); end

    # source://aws-partitions//lib/aws-partitions/metadata.rb#21
    def partitions; end
  end
end

# source://aws-partitions//lib/aws-partitions/partition.rb#5
class Aws::Partitions::Partition
  # source://aws-partitions//lib/aws-partitions/partition.rb#10
  def initialize(options = T.unsafe(nil)); end

  # source://aws-partitions//lib/aws-partitions/partition.rb#25
  def metadata; end

  # source://aws-partitions//lib/aws-partitions/partition.rb#19
  def name; end

  # source://aws-partitions//lib/aws-partitions/partition.rb#30
  def region(region_name); end

  # source://aws-partitions//lib/aws-partitions/partition.rb#47
  def region?(region_name); end

  # source://aws-partitions//lib/aws-partitions/partition.rb#22
  def region_regex; end

  # source://aws-partitions//lib/aws-partitions/partition.rb#41
  def regions; end

  # source://aws-partitions//lib/aws-partitions/partition.rb#54
  def service(service_name); end

  # source://aws-partitions//lib/aws-partitions/partition.rb#71
  def service?(service_name); end

  # source://aws-partitions//lib/aws-partitions/partition.rb#65
  def services; end

  class << self
    # source://aws-partitions//lib/aws-partitions/partition.rb#77
    def build(partition); end

    private

    # source://aws-partitions//lib/aws-partitions/partition.rb#90
    def build_regions(partition); end

    # source://aws-partitions//lib/aws-partitions/partition.rb#102
    def build_services(partition); end
  end
end

# source://aws-partitions//lib/aws-partitions/partition_list.rb#5
class Aws::Partitions::PartitionList
  include ::Enumerable

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#9
  def initialize; end

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#37
  def add_partition(partition); end

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#80
  def clear; end

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#14
  def each(&block); end

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#47
  def merge_metadata(partitions_metadata); end

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#20
  def partition(partition_name); end

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#31
  def partitions; end

  private

  # source://aws-partitions//lib/aws-partitions/partition_list.rb#86
  def build_metadata_regions(partition_name, metadata_regions, existing = T.unsafe(nil)); end

  class << self
    # source://aws-partitions//lib/aws-partitions/partition_list.rb#104
    def build(partitions); end
  end
end

# source://aws-partitions//lib/aws-partitions/region.rb#7
class Aws::Partitions::Region
  # source://aws-partitions//lib/aws-partitions/region.rb#14
  def initialize(options = T.unsafe(nil)); end

  # source://aws-partitions//lib/aws-partitions/region.rb#25
  def description; end

  # source://aws-partitions//lib/aws-partitions/region.rb#22
  def name; end

  # source://aws-partitions//lib/aws-partitions/region.rb#29
  def partition_name; end

  # source://aws-partitions//lib/aws-partitions/region.rb#34
  def services; end

  class << self
    # source://aws-partitions//lib/aws-partitions/region.rb#39
    def build(region_name, region, partition); end

    private

    # source://aws-partitions//lib/aws-partitions/region.rb#50
    def region_services(region_name, partition); end

    # source://aws-partitions//lib/aws-partitions/region.rb#61
    def service_in_region?(svc, region_name); end
  end
end

# source://aws-partitions//lib/aws-partitions/service.rb#7
class Aws::Partitions::Service
  # source://aws-partitions//lib/aws-partitions/service.rb#15
  def initialize(options = T.unsafe(nil)); end

  # source://aws-partitions//lib/aws-partitions/service.rb#42
  def dualstack_regions; end

  # source://aws-partitions//lib/aws-partitions/service.rb#38
  def fips_regions; end

  # source://aws-partitions//lib/aws-partitions/service.rb#27
  def name; end

  # source://aws-partitions//lib/aws-partitions/service.rb#30
  def partition_name; end

  # source://aws-partitions//lib/aws-partitions/service.rb#46
  def partition_region; end

  # source://aws-partitions//lib/aws-partitions/service.rb#55
  def regionalized?; end

  # source://aws-partitions//lib/aws-partitions/service.rb#34
  def regions; end

  class << self
    # source://aws-partitions//lib/aws-partitions/service.rb#62
    def build(service_name, service, partition); end

    private

    # source://aws-partitions//lib/aws-partitions/service.rb#97
    def partition_region(service); end

    # source://aws-partitions//lib/aws-partitions/service.rb#76
    def regions(service, partition); end

    # source://aws-partitions//lib/aws-partitions/service.rb#82
    def variant_regions(variant_name, service, partition); end
  end
end
