# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `aws-sigv4` gem.
# Please instead update this file by running `bin/tapioca gem aws-sigv4`.


# source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#3
module Aws
  class << self
    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#93
    def config; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#96
    def config=(config); end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#155
    def eager_autoload!(*args); end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#148
    def empty_connection_pools!; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#105
    def partition(partition_name); end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#110
    def partitions; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#86
    def shared_config; end

    # source://aws-sdk-core/3.229.0/lib/aws-sdk-core.rb#125
    def use_bundled_cert!; end
  end
end

# source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#4
module Aws::Sigv4; end

# source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#10
module Aws::Sigv4::AsymmetricCredentials
  class << self
    # source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#55
    def be_bytes_to_num(bytes); end

    # source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#62
    def bn_to_be_bytes(bn); end

    # source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#88
    def check_openssl_support!; end

    # source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#15
    def derive_asymmetric_key(access_key_id, secret_access_key); end

    # source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#74
    def generate_ec(public_key, d); end
  end
end

# source://aws-sigv4//lib/aws-sigv4/asymmetric_credentials.rb#12
Aws::Sigv4::AsymmetricCredentials::N_MINUS_2 = T.let(T.unsafe(nil), Integer)

# source://aws-sigv4//lib/aws-sigv4/credentials.rb#8
class Aws::Sigv4::Credentials
  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#13
  def initialize(options = T.unsafe(nil)); end

  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#25
  def access_key_id; end

  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#28
  def secret_access_key; end

  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#31
  def session_token; end

  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#35
  def set?; end
end

# source://aws-sigv4//lib/aws-sigv4/errors.rb#5
module Aws::Sigv4::Errors; end

# source://aws-sigv4//lib/aws-sigv4/errors.rb#7
class Aws::Sigv4::Errors::MissingCredentialsError < ::ArgumentError
  # source://aws-sigv4//lib/aws-sigv4/errors.rb#8
  def initialize(msg = T.unsafe(nil)); end
end

# source://aws-sigv4//lib/aws-sigv4/errors.rb#18
class Aws::Sigv4::Errors::MissingRegionError < ::ArgumentError
  # source://aws-sigv4//lib/aws-sigv4/errors.rb#19
  def initialize(*args); end
end

# source://aws-sigv4//lib/aws-sigv4/signature.rb#5
class Aws::Sigv4::Signature
  # source://aws-sigv4//lib/aws-sigv4/signature.rb#8
  def initialize(options); end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#27
  def canonical_request; end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#27
  def canonical_request=(_arg0); end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#33
  def content_sha256; end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#33
  def content_sha256=(_arg0); end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#39
  def extra; end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#39
  def extra=(_arg0); end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#24
  def headers; end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#24
  def headers=(_arg0); end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#36
  def signature; end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#36
  def signature=(_arg0); end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#30
  def string_to_sign; end

  # source://aws-sigv4//lib/aws-sigv4/signature.rb#30
  def string_to_sign=(_arg0); end
end

# source://aws-sigv4//lib/aws-sigv4/signer.rb#77
class Aws::Sigv4::Signer
  # source://aws-sigv4//lib/aws-sigv4/signer.rb#136
  def initialize(options = T.unsafe(nil)); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#174
  def apply_checksum_header; end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#166
  def credentials_provider; end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#414
  def presign_url(options); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#155
  def region; end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#152
  def service; end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#328
  def sign_event(prior_signature, payload, encoder); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#223
  def sign_request(request); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#170
  def unsigned_headers; end

  private

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#544
  def asymmetric_signature(creds, string_to_sign); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#632
  def canonical_header_value(value); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#620
  def canonical_headers(headers); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#480
  def canonical_request(http_method, url, headers, content_sha256); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#532
  def credential(credentials, date); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#523
  def credential_scope(date); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#760
  def credentials_set?(credentials); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#717
  def downcase_headers(headers); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#563
  def event_signature(secret_access_key, date, string_to_sign); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#509
  def event_string_to_sign(datetime, headers, payload, prior_signature, encoder); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#689
  def extract_credentials_provider(options); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#724
  def extract_expires_in(options); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#699
  def extract_http_method(request); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#681
  def extract_region(options); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#672
  def extract_service(options); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#708
  def extract_url(request); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#742
  def fetch_credentials; end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#668
  def hexhmac(key, value); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#664
  def hmac(key, value); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#636
  def host(uri); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#581
  def normalized_querystring(querystring); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#571
  def path(url); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#767
  def presigned_url_expiration(options, expiration, datetime); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#647
  def sha256_hexdigest(value); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#536
  def signature(secret_access_key, date, string_to_sign); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#610
  def signed_headers(headers); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#491
  def string_to_sign(datetime, canonical_request, algorithm); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#476
  def sts_algorithm; end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#734
  def uri_escape(string); end

  # source://aws-sigv4//lib/aws-sigv4/signer.rb#738
  def uri_escape_path(string); end

  class << self
    # source://aws-sigv4//lib/aws-sigv4/signer.rb#805
    def normalize_path(uri); end

    # source://aws-sigv4//lib/aws-sigv4/signer.rb#796
    def uri_escape(string); end

    # source://aws-sigv4//lib/aws-sigv4/signer.rb#791
    def uri_escape_path(path); end

    # source://aws-sigv4//lib/aws-sigv4/signer.rb#786
    def use_crt?; end
  end
end

# source://aws-sigv4//lib/aws-sigv4/credentials.rb#46
class Aws::Sigv4::StaticCredentialsProvider
  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#52
  def initialize(options = T.unsafe(nil)); end

  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#59
  def credentials; end

  # source://aws-sigv4//lib/aws-sigv4/credentials.rb#62
  def set?; end
end

# source://aws-sigv4//lib/aws-sigv4.rb#11
Aws::Sigv4::VERSION = T.let(T.unsafe(nil), String)
