# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bcrypt_pbkdf` gem.
# Please instead update this file by running `bin/tapioca gem bcrypt_pbkdf`.


# source://bcrypt_pbkdf//lib/bcrypt_pbkdf.rb#8
module BCryptPbkdf
  class << self
    # source://bcrypt_pbkdf//lib/bcrypt_pbkdf.rb#20
    def key(pass, salt, keylen, rounds); end
  end
end

class BCryptPbkdf::Engine
  class << self
    def __bc_crypt_hash(_arg0, _arg1); end
    def __bc_crypt_pbkdf(_arg0, _arg1, _arg2, _arg3); end
  end
end
