# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ed25519` gem.
# Please instead update this file by running `bin/tapioca gem ed25519`.


# source://ed25519//lib/ed25519/version.rb#3
module Ed25519
  private

  # source://ed25519//lib/ed25519.rb#48
  def self_test; end

  # source://ed25519//lib/ed25519.rb#40
  def validate_key_bytes(key_bytes); end

  class << self
    # source://ed25519//lib/ed25519.rb#26
    def provider; end

    # source://ed25519//lib/ed25519.rb#26
    def provider=(_arg0); end

    # source://ed25519//lib/ed25519.rb#48
    def self_test; end

    # source://ed25519//lib/ed25519.rb#40
    def validate_key_bytes(key_bytes); end
  end
end

# source://ed25519//lib/ed25519.rb#13
Ed25519::KEY_SIZE = T.let(T.unsafe(nil), Integer)

module Ed25519::Provider; end

module Ed25519::Provider::Ref10
  class << self
    def create_keypair(_arg0); end
    def sign(_arg0, _arg1); end
    def verify(_arg0, _arg1, _arg2); end
  end
end

# source://ed25519//lib/ed25519.rb#16
Ed25519::SIGNATURE_SIZE = T.let(T.unsafe(nil), Integer)

# source://ed25519//lib/ed25519.rb#22
class Ed25519::SelfTestFailure < ::StandardError; end

# source://ed25519//lib/ed25519/signing_key.rb#7
class Ed25519::SigningKey
  # source://ed25519//lib/ed25519/signing_key.rb#30
  def initialize(seed); end

  # source://ed25519//lib/ed25519/signing_key.rb#48
  def inspect; end

  # source://ed25519//lib/ed25519/signing_key.rb#8
  def keypair; end

  # source://ed25519//lib/ed25519/signing_key.rb#8
  def seed; end

  # source://ed25519//lib/ed25519/signing_key.rb#43
  def sign(message); end

  # source://ed25519//lib/ed25519/signing_key.rb#55
  def to_bytes; end

  # source://ed25519//lib/ed25519/signing_key.rb#55
  def to_str; end

  # source://ed25519//lib/ed25519/signing_key.rb#8
  def verify_key; end

  class << self
    # source://ed25519//lib/ed25519/signing_key.rb#18
    def from_keypair(keypair); end

    # source://ed25519//lib/ed25519/signing_key.rb#11
    def generate; end
  end
end

# source://ed25519//lib/ed25519/version.rb#4
Ed25519::VERSION = T.let(T.unsafe(nil), String)

# source://ed25519//lib/ed25519.rb#19
class Ed25519::VerifyError < ::StandardError; end

# source://ed25519//lib/ed25519/verify_key.rb#5
class Ed25519::VerifyKey
  # source://ed25519//lib/ed25519/verify_key.rb#9
  def initialize(key); end

  # source://ed25519//lib/ed25519/verify_key.rb#41
  def inspect; end

  # source://ed25519//lib/ed25519/verify_key.rb#35
  def to_bytes; end

  # source://ed25519//lib/ed25519/verify_key.rb#35
  def to_str; end

  # source://ed25519//lib/ed25519/verify_key.rb#22
  def verify(signature, message); end
end
