# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `google-protobuf` gem.
# Please instead update this file by running `bin/tapioca gem google-protobuf`.


# source://google-protobuf//lib/google/protobuf/message_exts.rb#8
module Google; end

# source://google-protobuf//lib/google/protobuf/message_exts.rb#9
module Google::Protobuf
  class << self
    # source://google-protobuf//lib/google/protobuf.rb#38
    def decode(klass, proto, options = T.unsafe(nil)); end

    # source://google-protobuf//lib/google/protobuf.rb#42
    def decode_json(klass, json, options = T.unsafe(nil)); end

    def deep_copy(_arg0); end
    def discard_unknown(_arg0); end

    # source://google-protobuf//lib/google/protobuf.rb#30
    def encode(msg, options = T.unsafe(nil)); end

    # source://google-protobuf//lib/google/protobuf.rb#34
    def encode_json(msg, options = T.unsafe(nil)); end
  end
end

# source://google-protobuf//lib/google/protobuf/message_exts.rb#33
class Google::Protobuf::AbstractMessage
  include ::Google::Protobuf::MessageExts
  extend ::Google::Protobuf::MessageExts::ClassMethods

  def initialize(*_arg0); end

  def ==(_arg0); end
  def [](_arg0); end
  def []=(_arg0, _arg1); end
  def clone; end
  def dup; end
  def eql?(_arg0); end
  def freeze; end
  def frozen?; end
  def hash; end
  def inspect; end
  def method_missing(*_arg0); end
  def to_h; end
  def to_s; end

  private

  def respond_to_missing?(*_arg0); end

  class << self
    def decode(*_arg0); end
    def decode_json(*_arg0); end
    def descriptor; end
    def encode(*_arg0); end
    def encode_json(*_arg0); end
  end
end

class Google::Protobuf::Any < ::Google::Protobuf::AbstractMessage; end

class Google::Protobuf::Descriptor
  include ::Enumerable

  def initialize(_arg0, _arg1, _arg2); end

  def each; end
  def each_oneof; end
  def file_descriptor; end
  def lookup(_arg0); end
  def lookup_oneof(_arg0); end
  def msgclass; end
  def name; end
  def options; end
  def to_proto; end
end

class Google::Protobuf::DescriptorPool
  def add_serialized_file(_arg0); end
  def lookup(_arg0); end

  class << self
    def generated_pool; end
  end
end

class Google::Protobuf::EnumDescriptor
  include ::Enumerable

  def initialize(_arg0, _arg1, _arg2); end

  def each; end
  def enummodule; end
  def file_descriptor; end
  def is_closed?; end
  def lookup_name(_arg0); end
  def lookup_value(_arg0); end
  def name; end
  def options; end
  def to_proto; end
end

# source://google-protobuf//lib/google/protobuf.rb#16
class Google::Protobuf::Error < ::StandardError; end

class Google::Protobuf::FieldDescriptor
  def initialize(_arg0, _arg1, _arg2); end

  def clear(_arg0); end
  def default; end
  def get(_arg0); end
  def has?(_arg0); end
  def has_presence?; end
  def is_packed?; end
  def json_name; end
  def label; end
  def name; end
  def number; end
  def options; end
  def repeated?; end
  def required?; end
  def set(_arg0, _arg1); end
  def submsg_name; end
  def subtype; end
  def to_proto; end
  def type; end
end

class Google::Protobuf::FileDescriptor
  def initialize(_arg0, _arg1, _arg2); end

  def name; end
  def options; end
  def to_proto; end
end

# source://google-protobuf//lib/google/protobuf.rb#46
Google::Protobuf::IMPLEMENTATION = T.let(T.unsafe(nil), Symbol)

# source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#10
module Google::Protobuf::Internal; end

class Google::Protobuf::Internal::Arena; end

# source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#42
class Google::Protobuf::Internal::LegacyObjectCache
  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#43
  def initialize; end

  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#49
  def get(key); end

  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#71
  def try_add(key, value); end

  private

  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#86
  def purge; end
end

Google::Protobuf::Internal::OBJECT_CACHE = T.let(T.unsafe(nil), Google::Protobuf::Internal::ObjectCache)

# source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#25
class Google::Protobuf::Internal::ObjectCache
  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#26
  def initialize; end

  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#31
  def get(key); end

  # source://google-protobuf//lib/google/protobuf/internal/object_cache.rb#35
  def try_add(key, value); end
end

Google::Protobuf::Internal::SIZEOF_LONG = T.let(T.unsafe(nil), Integer)
Google::Protobuf::Internal::SIZEOF_VALUE = T.let(T.unsafe(nil), Integer)

class Google::Protobuf::Map
  include ::Enumerable

  def initialize(*_arg0); end

  def ==(_arg0); end
  def [](_arg0); end
  def []=(_arg0, _arg1); end
  def clear; end
  def clone; end
  def delete(_arg0); end
  def dup; end
  def each; end
  def freeze; end
  def frozen?; end
  def has_key?(_arg0); end
  def hash; end
  def inspect; end
  def keys; end
  def length; end
  def merge(_arg0); end
  def size; end
  def to_h; end
  def values; end
end

# source://google-protobuf//lib/google/protobuf/message_exts.rb#10
module Google::Protobuf::MessageExts
  mixes_in_class_methods ::Google::Protobuf::MessageExts::ClassMethods

  # source://google-protobuf//lib/google/protobuf/message_exts.rb#28
  def to_hash; end

  # source://google-protobuf//lib/google/protobuf/message_exts.rb#20
  def to_json(options = T.unsafe(nil)); end

  # source://google-protobuf//lib/google/protobuf/message_exts.rb#24
  def to_proto(options = T.unsafe(nil)); end

  class << self
    # source://google-protobuf//lib/google/protobuf/message_exts.rb#13
    def included(klass); end
  end
end

# source://google-protobuf//lib/google/protobuf/message_exts.rb#17
module Google::Protobuf::MessageExts::ClassMethods; end

class Google::Protobuf::MethodDescriptor
  def initialize(_arg0, _arg1, _arg2); end

  def client_streaming; end
  def input_type; end
  def name; end
  def options; end
  def output_type; end
  def server_streaming; end
  def to_proto; end
end

class Google::Protobuf::OneofDescriptor
  include ::Enumerable

  def initialize(_arg0, _arg1, _arg2); end

  def each; end
  def name; end
  def options; end
  def to_proto; end
end

# source://google-protobuf//lib/google/protobuf.rb#20
Google::Protobuf::PREFER_FFI = T.let(T.unsafe(nil), FalseClass)

# source://google-protobuf//lib/google/protobuf.rb#17
class Google::Protobuf::ParseError < ::Google::Protobuf::Error; end

# source://google-protobuf//lib/google/protobuf/repeated_field.rb#27
class Google::Protobuf::RepeatedField
  include ::Enumerable
  extend ::Forwardable

  def initialize(*_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def &(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def *(*args, **_arg1, &block); end

  def +(_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def -(*args, **_arg1, &block); end

  def <<(_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def <=>(*args, **_arg1, &block); end

  def ==(_arg0); end
  def [](*_arg0); end
  def []=(_arg0, _arg1); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def assoc(*args, **_arg1, &block); end

  def at(*_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def bsearch(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def bsearch_index(*args, **_arg1, &block); end

  def clear; end
  def clone; end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def collect!(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def combination(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def compact(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def compact!(*args, &block); end

  def concat(_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def count(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def cycle(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#104
  def delete(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#104
  def delete_at(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def delete_if(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def difference(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def dig(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def drop(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def drop_while(*args, **_arg1, &block); end

  def dup; end
  def each; end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def each_index(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#92
  def empty?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def eql?(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def fetch(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def fill(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def find_index(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#58
  def first(n = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def flatten(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def flatten!(*args, &block); end

  def freeze; end
  def frozen?; end
  def hash; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def include?(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def index(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def insert(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def inspect(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def intersection(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def join(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def keep_if(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#69
  def last(n = T.unsafe(nil)); end

  def length; end
  def map; end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def map!(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def pack(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def permutation(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#81
  def pop(n = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def pretty_print(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def pretty_print_cycle(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def product(*args, **_arg1, &block); end

  def push(*_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def rassoc(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def reject!(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def repeated_combination(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def repeated_permutation(*args, **_arg1, &block); end

  def replace(_arg0); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def reverse(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def reverse!(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def rindex(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def rotate(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def rotate!(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def sample(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def select!(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def shelljoin(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#104
  def shift(*args, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def shuffle(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def shuffle!(*args, &block); end

  def size; end
  def slice(*_arg0); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#104
  def slice!(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def sort!(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def sort_by!(*args, &block); end

  def to_ary; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def to_s(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def transpose(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def union(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def uniq(*args, **_arg1, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#116
  def uniq!(*args, &block); end

  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#104
  def unshift(*args, &block); end

  def values_at; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def |(*args, **_arg1, &block); end

  private

  def pop_one; end

  class << self
    private

    # source://google-protobuf//lib/google/protobuf/repeated_field.rb#103
    def define_array_wrapper_method(method_name); end

    # source://google-protobuf//lib/google/protobuf/repeated_field.rb#115
    def define_array_wrapper_with_result_method(method_name); end
  end
end

# source://google-protobuf//lib/google/protobuf/repeated_field.rb#159
class Google::Protobuf::RepeatedField::ProxyingEnumerator < ::Struct
  # source://google-protobuf//lib/google/protobuf/repeated_field.rb#160
  def each(*args, &block); end
end

class Google::Protobuf::ServiceDescriptor
  include ::Enumerable

  def initialize(_arg0, _arg1, _arg2); end

  def each; end
  def file_descriptor; end
  def name; end
  def options; end
  def to_proto; end
end

# source://google-protobuf//lib/google/protobuf.rb#18
class Google::Protobuf::TypeError < ::TypeError; end
