# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `jmespath` gem.
# Please instead update this file by running `bin/tapioca gem jmespath`.


# source://jmespath//lib/jmespath.rb#6
module JMESPath
  class << self
    # source://jmespath//lib/jmespath.rb#35
    def load_json(path); end

    # source://jmespath//lib/jmespath.rb#24
    def search(expression, data, runtime_options = T.unsafe(nil)); end
  end
end

# source://jmespath//lib/jmespath/caching_parser.rb#5
class JMESPath::CachingParser
  # source://jmespath//lib/jmespath/caching_parser.rb#6
  def initialize(options = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/caching_parser.rb#12
  def parse(expression); end

  private

  # source://jmespath//lib/jmespath/caching_parser.rb#22
  def cache_expression(expression); end
end

# source://jmespath//lib/jmespath/errors.rb#4
module JMESPath::Errors; end

# source://jmespath//lib/jmespath/errors.rb#5
class JMESPath::Errors::Error < ::StandardError; end

# source://jmespath//lib/jmespath/errors.rb#15
class JMESPath::Errors::InvalidArityError < ::JMESPath::Errors::Error; end

# source://jmespath//lib/jmespath/errors.rb#11
class JMESPath::Errors::InvalidTypeError < ::JMESPath::Errors::Error; end

# source://jmespath//lib/jmespath/errors.rb#13
class JMESPath::Errors::InvalidValueError < ::JMESPath::Errors::Error; end

# source://jmespath//lib/jmespath/errors.rb#7
class JMESPath::Errors::RuntimeError < ::JMESPath::Errors::Error; end

# source://jmespath//lib/jmespath/errors.rb#9
class JMESPath::Errors::SyntaxError < ::JMESPath::Errors::Error; end

# source://jmespath//lib/jmespath/errors.rb#17
class JMESPath::Errors::UnknownFunctionError < ::JMESPath::Errors::Error; end

# source://jmespath//lib/jmespath/lexer.rb#7
class JMESPath::Lexer
  # source://jmespath//lib/jmespath/lexer.rb#163
  def tokenize(expression); end

  private

  # source://jmespath//lib/jmespath/lexer.rb#277
  def inside(chars, delim, type); end

  # source://jmespath//lib/jmespath/lexer.rb#268
  def match_or(chars, current, expected, type, or_type); end

  # source://jmespath//lib/jmespath/lexer.rb#346
  def parse_json(token, quoted = T.unsafe(nil)); end

  class << self
    # source://jmespath//lib/jmespath/lexer.rb#322
    def requires_wrapping?; end
  end
end

# source://jmespath//lib/jmespath/lexer.rb#364
class JMESPath::Lexer::CharacterStream
  # source://jmespath//lib/jmespath/lexer.rb#365
  def initialize(chars); end

  # source://jmespath//lib/jmespath/lexer.rb#370
  def current; end

  # source://jmespath//lib/jmespath/lexer.rb#374
  def next; end

  # source://jmespath//lib/jmespath/lexer.rb#379
  def position; end
end

# source://jmespath//lib/jmespath/lexer.rb#146
JMESPath::Lexer::NUMBERS = T.let(T.unsafe(nil), Set)

# source://jmespath//lib/jmespath/lexer.rb#148
JMESPath::Lexer::SIMPLE_TOKENS = T.let(T.unsafe(nil), Hash)

# source://jmespath//lib/jmespath/lexer.rb#47
JMESPath::Lexer::STATE_AND = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#45
JMESPath::Lexer::STATE_EQ = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#44
JMESPath::Lexer::STATE_GT = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#34
JMESPath::Lexer::STATE_IDENTIFIER = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#40
JMESPath::Lexer::STATE_JSON_LITERAL = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#41
JMESPath::Lexer::STATE_LBRACKET = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#43
JMESPath::Lexer::STATE_LT = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#46
JMESPath::Lexer::STATE_NOT = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#35
JMESPath::Lexer::STATE_NUMBER = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#42
JMESPath::Lexer::STATE_PIPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#39
JMESPath::Lexer::STATE_QUOTED_STRING = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#36
JMESPath::Lexer::STATE_SINGLE_CHAR = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#38
JMESPath::Lexer::STATE_STRING_LITERAL = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#37
JMESPath::Lexer::STATE_WHITESPACE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/lexer.rb#49
JMESPath::Lexer::TRANSLATION_TABLE = T.let(T.unsafe(nil), Hash)

# source://jmespath//lib/jmespath/lexer.rb#27
JMESPath::Lexer::T_AND = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#11
JMESPath::Lexer::T_COLON = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#10
JMESPath::Lexer::T_COMMA = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#32
JMESPath::Lexer::T_COMPARATOR = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#12
JMESPath::Lexer::T_CURRENT = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#8
JMESPath::Lexer::T_DOT = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#31
JMESPath::Lexer::T_EOF = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#13
JMESPath::Lexer::T_EXPREF = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#29
JMESPath::Lexer::T_FILTER = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#20
JMESPath::Lexer::T_FLATTEN = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#21
JMESPath::Lexer::T_IDENTIFIER = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#16
JMESPath::Lexer::T_LBRACE = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#18
JMESPath::Lexer::T_LBRACKET = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#30
JMESPath::Lexer::T_LITERAL = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#14
JMESPath::Lexer::T_LPAREN = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#28
JMESPath::Lexer::T_NOT = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#22
JMESPath::Lexer::T_NUMBER = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#26
JMESPath::Lexer::T_OR = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#25
JMESPath::Lexer::T_PIPE = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#23
JMESPath::Lexer::T_QUOTED_IDENTIFIER = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#17
JMESPath::Lexer::T_RBRACE = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#19
JMESPath::Lexer::T_RBRACKET = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#15
JMESPath::Lexer::T_RPAREN = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#9
JMESPath::Lexer::T_STAR = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#24
JMESPath::Lexer::T_UNKNOWN = T.let(T.unsafe(nil), Symbol)

# source://jmespath//lib/jmespath/lexer.rb#140
JMESPath::Lexer::VALID_IDENTIFIERS = T.let(T.unsafe(nil), Set)

# source://jmespath//lib/jmespath/nodes.rb#4
module JMESPath::Nodes; end

# source://jmespath//lib/jmespath/nodes/function.rb#87
class JMESPath::Nodes::AbsFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#90
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/and.rb#4
class JMESPath::Nodes::And < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/and.rb#5
  def initialize(left, right); end

  # source://jmespath//lib/jmespath/nodes/and.rb#19
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/and.rb#10
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/projection.rb#45
class JMESPath::Nodes::ArrayProjection < ::JMESPath::Nodes::Projection
  # source://jmespath//lib/jmespath/nodes/projection.rb#46
  def extract_targets(target); end

  # source://jmespath//lib/jmespath/nodes/projection.rb#50
  def fast_instance; end
end

# source://jmespath//lib/jmespath/nodes/function.rb#104
class JMESPath::Nodes::AvgFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#107
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#129
class JMESPath::Nodes::CeilFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#132
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/subexpression.rb#38
class JMESPath::Nodes::Chain
  # source://jmespath//lib/jmespath/nodes/subexpression.rb#39
  def initialize(children); end

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#49
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#43
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/field.rb#41
class JMESPath::Nodes::ChainedField < ::JMESPath::Nodes::Field
  # source://jmespath//lib/jmespath/nodes/field.rb#42
  def initialize(keys); end

  # source://jmespath//lib/jmespath/nodes/field.rb#66
  def chain(other); end

  # source://jmespath//lib/jmespath/nodes/field.rb#49
  def visit(obj); end

  private

  # source://jmespath//lib/jmespath/nodes/field.rb#72
  def keys; end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#5
class JMESPath::Nodes::Comparator < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/comparator.rb#10
  def initialize(left, right); end

  # source://jmespath//lib/jmespath/nodes/comparator.rb#8
  def left; end

  # source://jmespath//lib/jmespath/nodes/comparator.rb#33
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/comparator.rb#8
  def right; end

  # source://jmespath//lib/jmespath/nodes/comparator.rb#29
  def visit(value); end

  private

  # source://jmespath//lib/jmespath/nodes/comparator.rb#39
  def check(_left_value, _right_value); end

  # source://jmespath//lib/jmespath/nodes/comparator.rb#43
  def comparable?(left_value, right_value); end

  class << self
    # source://jmespath//lib/jmespath/nodes/comparator.rb#15
    def create(relation, left, right); end
  end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#6
JMESPath::Nodes::Comparator::COMPARABLE_TYPES = T.let(T.unsafe(nil), Array)

# source://jmespath//lib/jmespath/nodes/condition.rb#29
class JMESPath::Nodes::ComparatorCondition < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/condition.rb#33
  def initialize(left, right, child); end

  # source://jmespath//lib/jmespath/nodes/condition.rb#39
  def visit(_value); end

  private

  # source://jmespath//lib/jmespath/nodes/condition.rb#45
  def comparable?(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#31
JMESPath::Nodes::ComparatorCondition::COMPARABLE_TYPES = T.let(T.unsafe(nil), Array)

# source://jmespath//lib/jmespath/nodes/condition.rb#30
JMESPath::Nodes::ComparatorCondition::COMPARATOR_TO_CONDITION = T.let(T.unsafe(nil), Hash)

# source://jmespath//lib/jmespath/nodes/comparator.rb#50
module JMESPath::Nodes::Comparators; end

# source://jmespath//lib/jmespath/nodes/comparator.rb#51
class JMESPath::Nodes::Comparators::Eq < ::JMESPath::Nodes::Comparator
  # source://jmespath//lib/jmespath/nodes/comparator.rb#52
  def check(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#63
class JMESPath::Nodes::Comparators::Gt < ::JMESPath::Nodes::Comparator
  # source://jmespath//lib/jmespath/nodes/comparator.rb#64
  def check(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#69
class JMESPath::Nodes::Comparators::Gte < ::JMESPath::Nodes::Comparator
  # source://jmespath//lib/jmespath/nodes/comparator.rb#70
  def check(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#75
class JMESPath::Nodes::Comparators::Lt < ::JMESPath::Nodes::Comparator
  # source://jmespath//lib/jmespath/nodes/comparator.rb#76
  def check(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#81
class JMESPath::Nodes::Comparators::Lte < ::JMESPath::Nodes::Comparator
  # source://jmespath//lib/jmespath/nodes/comparator.rb#82
  def check(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/comparator.rb#57
class JMESPath::Nodes::Comparators::Neq < ::JMESPath::Nodes::Comparator
  # source://jmespath//lib/jmespath/nodes/comparator.rb#58
  def check(left_value, right_value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#503
module JMESPath::Nodes::CompareBy
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#506
  def compare_by(mode, *args); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#5
class JMESPath::Nodes::Condition < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/condition.rb#6
  def initialize(test, child); end

  # source://jmespath//lib/jmespath/nodes/condition.rb#19
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/condition.rb#11
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#146
class JMESPath::Nodes::ContainsFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#149
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/current.rb#5
class JMESPath::Nodes::Current < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/current.rb#6
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#558
class JMESPath::Nodes::EndsWithFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#563
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#52
class JMESPath::Nodes::EqCondition < ::JMESPath::Nodes::ComparatorCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#59
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/condition.rb#55
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/expression.rb#5
class JMESPath::Nodes::Expression < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/expression.rb#8
  def initialize(expression); end

  # source://jmespath//lib/jmespath/nodes/expression.rb#16
  def eval(value); end

  # source://jmespath//lib/jmespath/nodes/expression.rb#6
  def expression; end

  # source://jmespath//lib/jmespath/nodes/expression.rb#20
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/expression.rb#12
  def visit(_value); end
end

# source://jmespath//lib/jmespath/nodes/projection.rb#55
class JMESPath::Nodes::FastArrayProjection < ::JMESPath::Nodes::ArrayProjection
  include ::JMESPath::Nodes::FastProjector
end

# source://jmespath//lib/jmespath/nodes/projection.rb#73
class JMESPath::Nodes::FastObjectProjection < ::JMESPath::Nodes::ObjectProjection
  include ::JMESPath::Nodes::FastProjector
end

# source://jmespath//lib/jmespath/nodes/projection.rb#37
module JMESPath::Nodes::FastProjector
  # source://jmespath//lib/jmespath/nodes/projection.rb#38
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/field.rb#5
class JMESPath::Nodes::Field < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/field.rb#6
  def initialize(key); end

  # source://jmespath//lib/jmespath/nodes/field.rb#30
  def chain(other); end

  # source://jmespath//lib/jmespath/nodes/field.rb#26
  def chains_with?(other); end

  # source://jmespath//lib/jmespath/nodes/field.rb#11
  def visit(value); end

  protected

  # source://jmespath//lib/jmespath/nodes/field.rb#36
  def keys; end
end

# source://jmespath//lib/jmespath/nodes/flatten.rb#5
class JMESPath::Nodes::Flatten < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/flatten.rb#6
  def initialize(child); end

  # source://jmespath//lib/jmespath/nodes/flatten.rb#23
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/flatten.rb#10
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#166
class JMESPath::Nodes::FloorFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#169
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#5
class JMESPath::Nodes::Function < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/function.rb#8
  def initialize(children, options = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/nodes/function.rb#26
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/function.rb#22
  def visit(value); end

  private

  # source://jmespath//lib/jmespath/nodes/function.rb#44
  def call(_args); end

  # source://jmespath//lib/jmespath/nodes/function.rb#40
  def maybe_raise(error_type, message); end

  class << self
    # source://jmespath//lib/jmespath/nodes/function.rb#14
    def create(name, children, options = T.unsafe(nil)); end
  end
end

# source://jmespath//lib/jmespath/nodes/function.rb#6
JMESPath::Nodes::Function::FUNCTIONS = T.let(T.unsafe(nil), Hash)

# source://jmespath//lib/jmespath/nodes/function.rb#30
class JMESPath::Nodes::Function::FunctionName
  # source://jmespath//lib/jmespath/nodes/function.rb#33
  def initialize(name); end

  # source://jmespath//lib/jmespath/nodes/function.rb#31
  def name; end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#106
class JMESPath::Nodes::GtCondition < ::JMESPath::Nodes::ComparatorCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#109
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#116
class JMESPath::Nodes::GteCondition < ::JMESPath::Nodes::ComparatorCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#119
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/index.rb#5
JMESPath::Nodes::Index = JMESPath::Nodes::Field

# source://jmespath//lib/jmespath/nodes/function.rb#351
class JMESPath::Nodes::JoinFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#354
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#311
class JMESPath::Nodes::KeysFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#314
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#183
class JMESPath::Nodes::LengthFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#186
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/literal.rb#5
class JMESPath::Nodes::Literal < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/literal.rb#8
  def initialize(value); end

  # source://jmespath//lib/jmespath/nodes/literal.rb#6
  def value; end

  # source://jmespath//lib/jmespath/nodes/literal.rb#12
  def visit(_value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#68
class JMESPath::Nodes::LiteralRightEqCondition < ::JMESPath::Nodes::EqCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#69
  def initialize(left, right, child); end

  # source://jmespath//lib/jmespath/nodes/condition.rb#74
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#95
class JMESPath::Nodes::LiteralRightNeqCondition < ::JMESPath::Nodes::NeqCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#96
  def initialize(left, right, child); end

  # source://jmespath//lib/jmespath/nodes/condition.rb#101
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#126
class JMESPath::Nodes::LtCondition < ::JMESPath::Nodes::ComparatorCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#129
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#136
class JMESPath::Nodes::LteCondition < ::JMESPath::Nodes::ComparatorCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#139
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#204
class JMESPath::Nodes::Map < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#207
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#538
class JMESPath::Nodes::MaxByFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker
  include ::JMESPath::Nodes::CompareBy

  # source://jmespath//lib/jmespath/nodes/function.rb#543
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#225
class JMESPath::Nodes::MaxFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#230
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#610
class JMESPath::Nodes::MergeFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#613
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#548
class JMESPath::Nodes::MinByFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker
  include ::JMESPath::Nodes::CompareBy

  # source://jmespath//lib/jmespath/nodes/function.rb#553
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#261
class JMESPath::Nodes::MinFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#266
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#5
class JMESPath::Nodes::MultiSelectHash < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#6
  def initialize(kv_pairs); end

  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#20
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#10
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#24
class JMESPath::Nodes::MultiSelectHash::KeyValuePair
  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#27
  def initialize(key, value); end

  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#25
  def key; end

  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#32
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/multi_select_hash.rb#25
  def value; end
end

# source://jmespath//lib/jmespath/nodes/multi_select_list.rb#5
class JMESPath::Nodes::MultiSelectList < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/multi_select_list.rb#6
  def initialize(children); end

  # source://jmespath//lib/jmespath/nodes/multi_select_list.rb#18
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/multi_select_list.rb#10
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/condition.rb#79
class JMESPath::Nodes::NeqCondition < ::JMESPath::Nodes::ComparatorCondition
  # source://jmespath//lib/jmespath/nodes/condition.rb#86
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/condition.rb#82
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes.rb#5
class JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes.rb#13
  def chains_with?(_other); end

  # source://jmespath//lib/jmespath/nodes.rb#9
  def optimize; end

  # source://jmespath//lib/jmespath/nodes.rb#6
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/not.rb#4
class JMESPath::Nodes::Not < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/not.rb#5
  def initialize(expression); end

  # source://jmespath//lib/jmespath/nodes/not.rb#13
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/not.rb#9
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#419
class JMESPath::Nodes::NotNullFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#422
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/projection.rb#59
class JMESPath::Nodes::ObjectProjection < ::JMESPath::Nodes::Projection
  # source://jmespath//lib/jmespath/nodes/projection.rb#60
  def extract_targets(target); end

  # source://jmespath//lib/jmespath/nodes/projection.rb#68
  def fast_instance; end
end

# source://jmespath//lib/jmespath/nodes/or.rb#5
class JMESPath::Nodes::Or < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/or.rb#6
  def initialize(left, right); end

  # source://jmespath//lib/jmespath/nodes/or.rb#20
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/or.rb#11
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/pipe.rb#5
JMESPath::Nodes::Pipe = JMESPath::Nodes::Subexpression

# source://jmespath//lib/jmespath/nodes/projection.rb#5
class JMESPath::Nodes::Projection < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/projection.rb#6
  def initialize(target, projection); end

  # source://jmespath//lib/jmespath/nodes/projection.rb#22
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/projection.rb#11
  def visit(value); end

  private

  # source://jmespath//lib/jmespath/nodes/projection.rb#32
  def extract_targets(_left_value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#624
class JMESPath::Nodes::ReverseFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#627
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/slice.rb#74
class JMESPath::Nodes::SimpleSlice < ::JMESPath::Nodes::Slice
  # source://jmespath//lib/jmespath/nodes/slice.rb#75
  def initialize(start, stop); end

  # source://jmespath//lib/jmespath/nodes/slice.rb#79
  def visit(value); end
end

# source://jmespath//lib/jmespath/nodes/slice.rb#5
class JMESPath::Nodes::Slice < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/slice.rb#6
  def initialize(start, stop, step); end

  # source://jmespath//lib/jmespath/nodes/slice.rb#34
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/slice.rb#13
  def visit(value); end

  private

  # source://jmespath//lib/jmespath/nodes/slice.rb#61
  def adjust_endpoint(length, endpoint, step); end

  # source://jmespath//lib/jmespath/nodes/slice.rb#44
  def adjust_slice(length, start, stop, step); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#467
class JMESPath::Nodes::SortByFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#472
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#431
class JMESPath::Nodes::SortFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#436
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#584
class JMESPath::Nodes::StartsWithFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#589
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/subexpression.rb#5
class JMESPath::Nodes::Subexpression < ::JMESPath::Nodes::Node
  # source://jmespath//lib/jmespath/nodes/subexpression.rb#6
  def initialize(left, right); end

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#15
  def optimize; end

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#11
  def visit(value); end

  protected

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#23
  def flatten; end

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#21
  def left; end

  # source://jmespath//lib/jmespath/nodes/subexpression.rb#21
  def right; end
end

# source://jmespath//lib/jmespath/nodes/function.rb#401
class JMESPath::Nodes::SumFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#404
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#644
class JMESPath::Nodes::ToArrayFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#647
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#384
class JMESPath::Nodes::ToNumberFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#387
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#371
class JMESPath::Nodes::ToStringFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#374
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#49
module JMESPath::Nodes::TypeChecker
  # source://jmespath//lib/jmespath/nodes/function.rb#50
  def get_type(value); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#68
JMESPath::Nodes::TypeChecker::ARRAY_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#69
JMESPath::Nodes::TypeChecker::BOOLEAN_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#70
JMESPath::Nodes::TypeChecker::EXPRESSION_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#71
JMESPath::Nodes::TypeChecker::NULL_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#72
JMESPath::Nodes::TypeChecker::NUMBER_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#73
JMESPath::Nodes::TypeChecker::OBJECT_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#74
JMESPath::Nodes::TypeChecker::STRING_TYPE = T.let(T.unsafe(nil), Integer)

# source://jmespath//lib/jmespath/nodes/function.rb#76
JMESPath::Nodes::TypeChecker::TYPE_NAMES = T.let(T.unsafe(nil), Hash)

# source://jmespath//lib/jmespath/nodes/function.rb#297
class JMESPath::Nodes::TypeFunction < ::JMESPath::Nodes::Function
  include ::JMESPath::Nodes::TypeChecker

  # source://jmespath//lib/jmespath/nodes/function.rb#302
  def call(args); end
end

# source://jmespath//lib/jmespath/nodes/function.rb#330
class JMESPath::Nodes::ValuesFunction < ::JMESPath::Nodes::Function
  # source://jmespath//lib/jmespath/nodes/function.rb#333
  def call(args); end
end

# source://jmespath//lib/jmespath/parser.rb#6
class JMESPath::Parser
  # source://jmespath//lib/jmespath/parser.rb#30
  def initialize(options = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/parser.rb#48
  def method_missing(method_name, *args); end

  # source://jmespath//lib/jmespath/parser.rb#36
  def parse(expression); end

  private

  # source://jmespath//lib/jmespath/parser.rb#60
  def expr(stream, rbp = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/parser.rb#230
  def led_and(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#160
  def led_comparator(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#167
  def led_dot(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#177
  def led_filter(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#190
  def led_flatten(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#197
  def led_lbracket(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#208
  def led_lparen(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#224
  def led_or(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#236
  def led_pipe(stream, left); end

  # source://jmespath//lib/jmespath/parser.rb#68
  def nud_current(stream); end

  # source://jmespath//lib/jmespath/parser.rb#73
  def nud_expref(stream); end

  # source://jmespath//lib/jmespath/parser.rb#93
  def nud_filter(stream); end

  # source://jmespath//lib/jmespath/parser.rb#97
  def nud_flatten(stream); end

  # source://jmespath//lib/jmespath/parser.rb#101
  def nud_identifier(stream); end

  # source://jmespath//lib/jmespath/parser.rb#111
  def nud_lbrace(stream); end

  # source://jmespath//lib/jmespath/parser.rb#123
  def nud_lbracket(stream); end

  # source://jmespath//lib/jmespath/parser.rb#135
  def nud_literal(stream); end

  # source://jmespath//lib/jmespath/parser.rb#83
  def nud_lparen(stream); end

  # source://jmespath//lib/jmespath/parser.rb#78
  def nud_not(stream); end

  # source://jmespath//lib/jmespath/parser.rb#141
  def nud_quoted_identifier(stream); end

  # source://jmespath//lib/jmespath/parser.rb#152
  def nud_star(stream); end

  # source://jmespath//lib/jmespath/parser.rb#156
  def nud_unknown(stream); end

  # source://jmespath//lib/jmespath/parser.rb#243
  def parse_array_index_expression(stream); end

  # source://jmespath//lib/jmespath/parser.rb#274
  def parse_dot(stream, binding_power); end

  # source://jmespath//lib/jmespath/parser.rb#283
  def parse_key_value_pair(stream); end

  # source://jmespath//lib/jmespath/parser.rb#290
  def parse_multi_select_list(stream); end

  # source://jmespath//lib/jmespath/parser.rb#305
  def parse_projection(stream, binding_power); end

  # source://jmespath//lib/jmespath/parser.rb#319
  def parse_wildcard_array(stream, left = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/parser.rb#327
  def parse_wildcard_object(stream, left = T.unsafe(nil)); end
end

# source://jmespath//lib/jmespath/parser.rb#7
JMESPath::Parser::AFTER_DOT = T.let(T.unsafe(nil), Set)

# source://jmespath//lib/jmespath/parser.rb#22
JMESPath::Parser::COLON_RBRACKET = T.let(T.unsafe(nil), Set)

# source://jmespath//lib/jmespath/parser.rb#27
JMESPath::Parser::CURRENT_NODE = T.let(T.unsafe(nil), JMESPath::Nodes::Current)

# source://jmespath//lib/jmespath/parser.rb#16
JMESPath::Parser::NUM_COLON_RBRACKET = T.let(T.unsafe(nil), Set)

# source://jmespath//lib/jmespath/runtime.rb#4
class JMESPath::Runtime
  # source://jmespath//lib/jmespath/runtime.rb#45
  def initialize(options = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/runtime.rb#50
  def parser; end

  # source://jmespath//lib/jmespath/runtime.rb#55
  def search(expression, data); end

  private

  # source://jmespath//lib/jmespath/runtime.rb#62
  def default_parser(options); end
end

# source://jmespath//lib/jmespath/runtime.rb#6
JMESPath::Runtime::DEFAULT_PARSER = JMESPath::CachingParser

# source://jmespath//lib/jmespath/token.rb#4
class JMESPath::Token < ::Struct
  # source://jmespath//lib/jmespath/token.rb#37
  def initialize(type, value, position); end
end

# source://jmespath//lib/jmespath/token.rb#7
JMESPath::Token::BINDING_POWER = T.let(T.unsafe(nil), Hash)

# source://jmespath//lib/jmespath/token.rb#5
JMESPath::Token::NULL_TOKEN = T.let(T.unsafe(nil), JMESPath::Token)

# source://jmespath//lib/jmespath/token_stream.rb#4
class JMESPath::TokenStream
  # source://jmespath//lib/jmespath/token_stream.rb#7
  def initialize(expression, tokens); end

  # source://jmespath//lib/jmespath/token_stream.rb#16
  def expression; end

  # source://jmespath//lib/jmespath/token_stream.rb#35
  def inspect; end

  # source://jmespath//lib/jmespath/token_stream.rb#30
  def lookahead(count); end

  # source://jmespath//lib/jmespath/token_stream.rb#26
  def next(options = T.unsafe(nil)); end

  # source://jmespath//lib/jmespath/token_stream.rb#22
  def position; end

  # source://jmespath//lib/jmespath/token_stream.rb#19
  def token; end

  private

  # source://jmespath//lib/jmespath/token_stream.rb#46
  def _next; end

  # source://jmespath//lib/jmespath/token_stream.rb#51
  def validate_match(token, match); end
end

# source://jmespath//lib/jmespath/util.rb#4
module JMESPath::Util
  class << self
    # source://jmespath//lib/jmespath/util.rb#19
    def as_json(value); end

    # source://jmespath//lib/jmespath/util.rb#10
    def falsey?(value); end
  end
end

# source://jmespath//lib/jmespath/version.rb#3
JMESPath::VERSION = T.let(T.unsafe(nil), String)
