# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `net-scp` gem.
# Please instead update this file by running `bin/tapioca gem net-scp`.


# source://net-scp//lib/net/scp/errors.rb#1
class Net::SCP
  include ::Net::SSH::Loggable
  include ::Net::SCP::Download
  include ::Net::SCP::Upload

  # source://net-scp//lib/net/scp.rb#251
  def initialize(session); end

  # source://net-scp//lib/net/scp.rb#304
  def download(remote, local, options = T.unsafe(nil), &progress); end

  # source://net-scp//lib/net/scp.rb#319
  def download!(remote, local = T.unsafe(nil), options = T.unsafe(nil), &progress); end

  # source://net-scp//lib/net/scp.rb#247
  def session; end

  # source://net-scp//lib/net/scp.rb#276
  def upload(local, remote, options = T.unsafe(nil), &progress); end

  # source://net-scp//lib/net/scp.rb#283
  def upload!(local, remote, options = T.unsafe(nil), &progress); end

  private

  # source://net-scp//lib/net/scp.rb#396
  def await_response(channel, next_state); end

  # source://net-scp//lib/net/scp.rb#409
  def await_response_state(channel); end

  # source://net-scp//lib/net/scp.rb#420
  def finish_state(channel); end

  # source://net-scp//lib/net/scp.rb#426
  def progress_callback(channel, name, sent, total); end

  # source://net-scp//lib/net/scp.rb#331
  def scp_command(mode, options); end

  # source://net-scp//lib/net/scp.rb#431
  def shellescape(path); end

  # source://net-scp//lib/net/scp.rb#344
  def start_command(mode, local, remote, options = T.unsafe(nil), &callback); end

  class << self
    # source://net-scp//lib/net/scp.rb#238
    def download!(host, username, remote, local = T.unsafe(nil), options = T.unsafe(nil), &progress); end

    # source://net-scp//lib/net/scp.rb#201
    def start(host, username, options = T.unsafe(nil)); end

    # source://net-scp//lib/net/scp.rb#224
    def upload!(host, username, local, remote, options = T.unsafe(nil), &progress); end
  end
end

# source://net-scp//lib/net/scp/download.rb#8
module Net::SCP::Download
  private

  # source://net-scp//lib/net/scp/download.rb#17
  def download_start_state(channel); end

  # source://net-scp//lib/net/scp/download.rb#77
  def finish_read_state(channel); end

  # source://net-scp//lib/net/scp/download.rb#94
  def parse_directive(text); end

  # source://net-scp//lib/net/scp/download.rb#64
  def read_data_state(channel); end

  # source://net-scp//lib/net/scp/download.rb#34
  def read_directive_state(channel); end

  # source://net-scp//lib/net/scp/download.rb#124
  def read_directory(channel, directive); end

  # source://net-scp//lib/net/scp/download.rb#147
  def read_file(channel, directive); end
end

# source://net-scp//lib/net/scp/errors.rb#3
class Net::SCP::Error < ::RuntimeError; end

# source://net-scp//lib/net/scp/upload.rb#8
module Net::SCP::Upload
  private

  # source://net-scp//lib/net/scp/upload.rb#92
  def next_item_state(channel); end

  # source://net-scp//lib/net/scp/upload.rb#126
  def preserve_attributes_if_requested(channel); end

  # source://net-scp//lib/net/scp/upload.rb#74
  def send_data_state(channel); end

  # source://net-scp//lib/net/scp/upload.rb#110
  def set_current(channel, path); end

  # source://net-scp//lib/net/scp/upload.rb#31
  def upload_current_state(channel); end

  # source://net-scp//lib/net/scp/upload.rb#46
  def upload_directory_state(channel); end

  # source://net-scp//lib/net/scp/upload.rb#59
  def upload_file_state(channel); end

  # source://net-scp//lib/net/scp/upload.rb#17
  def upload_start_state(channel); end
end

# source://net-scp//lib/net/scp/upload.rb#13
Net::SCP::Upload::DEFAULT_CHUNK_SIZE = T.let(T.unsafe(nil), Integer)

module Net::SSH::Connection; end

# source://net-scp//lib/net/scp.rb#456
class Net::SSH::Connection::Session
  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#68
  def initialize(transport, options = T.unsafe(nil)); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#94
  def [](key); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#99
  def []=(key, value); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#152
  def busy?(include_invisible = T.unsafe(nil)); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#51
  def channel_open_handlers; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#44
  def channels; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#522
  def cleanup_channel(channel); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#121
  def close; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#114
  def closed?; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#255
  def ev_do_calculate_rw_wait(wait); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#270
  def ev_do_handle_events(readers, writers); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#289
  def ev_do_postprocess(was_events); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#248
  def ev_preprocess(&block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#379
  def exec(command, status: T.unsafe(nil), &block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#420
  def exec!(command, status: T.unsafe(nil), &block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#493
  def forward; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#105
  def host; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#481
  def listen_to(io, &callback); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#47
  def listeners; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#177
  def loop(wait = T.unsafe(nil), &block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#532
  def max_select_wait_time; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#517
  def on_global_request(type, &block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#507
  def on_open_channel(type, &block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#338
  def open_channel(type = T.unsafe(nil), *extra, &on_confirm); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#38
  def options; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#54
  def pending_requests; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#262
  def postprocess(readers, writers); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#237
  def preprocess(&block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#225
  def process(wait = T.unsafe(nil), &block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#41
  def properties; end

  # source://net-scp//lib/net/scp.rb#459
  def scp; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#311
  def send_global_request(type, *extra, &callback); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#443
  def send_message(message); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#136
  def shutdown!; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#487
  def stop_listening_to(io); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#35
  def transport; end

  private

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#682
  def channel_close(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#568
  def channel_closed(channel); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#667
  def channel_data(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#677
  def channel_eof(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#672
  def channel_extended_data(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#694
  def channel_failure(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#612
  def channel_open(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#645
  def channel_open_confirmation(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#651
  def channel_open_failure(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#662
  def channel_request(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#689
  def channel_success(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#657
  def channel_window_adjust(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#545
  def dispatch_incoming_packets(raise_disconnect_errors: T.unsafe(nil)); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#539
  def each_channel(&block); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#562
  def force_channel_cleanup_on_close; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#558
  def get_next_channel_id; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#579
  def global_request(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#699
  def io_select_wait(wait); end

  def loop_forever; end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#602
  def request_failure(packet); end

  # source://net-ssh/7.3.0/lib/net/ssh/connection/session.rb#595
  def request_success(packet); end
end
