# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-excon` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-excon`.


# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/concerns/untraced_hosts.rb#9
module OpenTelemetry::Instrumentation::Concerns; end

# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/concerns/untraced_hosts.rb#13
module OpenTelemetry::Instrumentation::Concerns::UntracedHosts
  # source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/concerns/untraced_hosts.rb#27
  def untraced?(host); end

  private

  # source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/concerns/untraced_hosts.rb#33
  def untraced_host?(host); end

  class << self
    # source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/concerns/untraced_hosts.rb#14
    def included(klass); end
  end
end

# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/excon.rb#13
module OpenTelemetry::Instrumentation::Excon; end

# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/excon/instrumentation.rb#14
class OpenTelemetry::Instrumentation::Excon::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  include ::OpenTelemetry::Instrumentation::Concerns::UntracedHosts

  private

  # source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/excon/instrumentation.rb#36
  def add_middleware; end

  # source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/excon/instrumentation.rb#40
  def patch; end

  # source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/excon/instrumentation.rb#31
  def require_dependencies; end
end

# source://opentelemetry-instrumentation-excon//lib/opentelemetry/instrumentation/excon/version.rb#10
OpenTelemetry::Instrumentation::Excon::VERSION = T.let(T.unsafe(nil), String)
