# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-pg` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-pg`.


# source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg.rb#14
module OpenTelemetry::Instrumentation::PG
  extend ::OpenTelemetry::Helpers::Sql
end

# source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg/instrumentation.rb#11
class OpenTelemetry::Instrumentation::PG::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg/instrumentation.rb#33
  def gem_version; end

  # source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg/instrumentation.rb#41
  def patch_client; end

  # source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg/instrumentation.rb#37
  def require_dependencies; end
end

# source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg/instrumentation.rb#12
OpenTelemetry::Instrumentation::PG::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-pg//lib/opentelemetry/instrumentation/pg/version.rb#10
OpenTelemetry::Instrumentation::PG::VERSION = T.let(T.unsafe(nil), String)
