# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-net_http` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-net_http`.


# source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation/net/http.rb#13
module OpenTelemetry::Instrumentation::Net; end

# source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation/net/http.rb#15
module OpenTelemetry::Instrumentation::Net::HTTP; end

# source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation/net/http/instrumentation.rb#13
class OpenTelemetry::Instrumentation::Net::HTTP::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation/net/http/instrumentation.rb#37
  def patch; end

  # source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation/net/http/instrumentation.rb#33
  def require_dependencies; end
end

# source://opentelemetry-instrumentation-net_http//lib/opentelemetry/instrumentation/net/http/version.rb#11
OpenTelemetry::Instrumentation::Net::HTTP::VERSION = T.let(T.unsafe(nil), String)
