# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-redis` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-redis`.


# source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis.rb#14
module OpenTelemetry::Instrumentation::Redis
  extend ::OpenTelemetry::Instrumentation::Redis

  # source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis.rb#26
  def attributes(context = T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis.rb#36
  def context_with_attributes(attributes_hash, parent_context: T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis.rb#50
  def with_attributes(attributes_hash); end
end

# source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis.rb#17
OpenTelemetry::Instrumentation::Redis::CURRENT_ATTRIBUTES_HASH = T.let(T.unsafe(nil), OpenTelemetry::Context::Key)

# source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis/instrumentation.rb#12
class OpenTelemetry::Instrumentation::Redis::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis/instrumentation.rb#33
  def patch_client; end

  # source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis/instrumentation.rb#28
  def require_dependencies; end
end

# source://opentelemetry-instrumentation-redis//lib/opentelemetry/instrumentation/redis/version.rb#10
OpenTelemetry::Instrumentation::Redis::VERSION = T.let(T.unsafe(nil), String)
