# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-active_job` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-active_job`.


# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation.rb#15
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job.rb#13
module OpenTelemetry::Instrumentation::ActiveJob
  extend ::OpenTelemetry::Instrumentation::ActiveJob

  # source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job.rb#33
  def context_with_span(span, parent_context: T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job.rb#23
  def current_span(context = T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job.rb#44
  def with_span(span); end
end

# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job.rb#16
OpenTelemetry::Instrumentation::ActiveJob::CURRENT_SPAN_KEY = T.let(T.unsafe(nil), OpenTelemetry::Context::Key)

# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job/instrumentation.rb#11
class OpenTelemetry::Instrumentation::ActiveJob::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job/instrumentation.rb#61
  def gem_version; end

  # source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job/instrumentation.rb#71
  def patch_activejob; end

  # source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job/instrumentation.rb#65
  def require_dependencies; end
end

# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job/instrumentation.rb#12
OpenTelemetry::Instrumentation::ActiveJob::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-active_job//lib/opentelemetry/instrumentation/active_job/version.rb#10
OpenTelemetry::Instrumentation::ActiveJob::VERSION = T.let(T.unsafe(nil), String)
