# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-action_pack` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-action_pack`.


# source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation.rb#15
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack.rb#13
module OpenTelemetry::Instrumentation::ActionPack; end

# source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/instrumentation.rb#35
class OpenTelemetry::Instrumentation::ActionPack::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/instrumentation.rb#56
  def gem_version; end

  # source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/instrumentation.rb#60
  def patch; end

  # source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/instrumentation.rb#64
  def require_dependencies; end

  # source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/instrumentation.rb#68
  def require_railtie; end
end

# source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/instrumentation.rb#36
OpenTelemetry::Instrumentation::ActionPack::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-action_pack//lib/opentelemetry/instrumentation/action_pack/version.rb#10
OpenTelemetry::Instrumentation::ActionPack::VERSION = T.let(T.unsafe(nil), String)
