# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-rdkafka` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-rdkafka`.


# source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation.rb#15
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation/rdkafka.rb#13
module OpenTelemetry::Instrumentation::Rdkafka; end

# source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation/rdkafka/instrumentation.rb#11
class OpenTelemetry::Instrumentation::Rdkafka::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation/rdkafka/instrumentation.rb#33
  def patch; end

  # source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation/rdkafka/instrumentation.rb#28
  def require_patches; end
end

# source://opentelemetry-instrumentation-rdkafka//lib/opentelemetry/instrumentation/rdkafka/version.rb#10
OpenTelemetry::Instrumentation::Rdkafka::VERSION = T.let(T.unsafe(nil), String)
