# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-base` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-base`.


# source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#7
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#8
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#62
class OpenTelemetry::Instrumentation::Base
  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#197
  def initialize(name, version, install_blk, present_blk, compatible_blk, options); end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#246
  def compatible?; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#192
  def config; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#257
  def enabled?(config = T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#216
  def install(config = T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#232
  def installable?(config = T.unsafe(nil)); end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#192
  def installed; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#192
  def installed?; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#192
  def name; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#238
  def present?; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#192
  def tracer; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#192
  def version; end

  private

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#363
  def coerce_env_var(env_var, validation_type); end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#272
  def config_options(user_config); end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#341
  def config_overrides_from_env; end

  # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#319
  def enabled_by_env_var?; end

  class << self
    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#136
    def compatible(&blk); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#77
    def inherited(subclass); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#116
    def install(&blk); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#165
    def instance; end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#87
    def instrumentation_name(instrumentation_name = T.unsafe(nil)); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#102
    def instrumentation_version(instrumentation_version = T.unsafe(nil)); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#148
    def option(name, default:, validate:); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#126
    def present(&blk); end

    private

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#172
    def compatible_blk; end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#174
    def infer_name; end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#180
    def infer_version; end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#172
    def install_blk; end

    def new(*_arg0); end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#172
    def options; end

    # source://opentelemetry-instrumentation-base//lib/opentelemetry/instrumentation/base.rb#172
    def present_blk; end
  end
end
