# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-aws_sdk` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-aws_sdk`.


# source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk.rb#13
module OpenTelemetry::Instrumentation::AwsSdk; end

# source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#36
class OpenTelemetry::Instrumentation::AwsSdk::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#56
  def gem_version; end

  private

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#76
  def add_plugins(*targets); end

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#119
  def loaded_service?(constant, service_module); end

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#100
  def loaded_service_clients; end

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#96
  def patch_telemetry_plugin; end

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#68
  def require_dependencies; end

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#84
  def supports_telemetry_plugin?(klass); end

  # source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#89
  def telemetry_plugin?; end
end

# source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/instrumentation.rb#37
OpenTelemetry::Instrumentation::AwsSdk::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-aws_sdk//lib/opentelemetry/instrumentation/aws_sdk/version.rb#10
OpenTelemetry::Instrumentation::AwsSdk::VERSION = T.let(T.unsafe(nil), String)
