# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-action_mailer` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-action_mailer`.


# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation.rb#15
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer.rb#13
module OpenTelemetry::Instrumentation::ActionMailer; end

# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#57
class OpenTelemetry::Instrumentation::ActionMailer::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#112
  def _config; end

  # source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#93
  def ecs_mail_convention; end

  # source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#83
  def gem_version; end

  # source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#130
  def require_dependencies; end

  # source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#87
  def resolve_email_address; end

  # source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#117
  def transform_payload(payload); end
end

# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#59
OpenTelemetry::Instrumentation::ActionMailer::Instrumentation::EMAIL_ATTRIBUTE = T.let(T.unsafe(nil), Array)

# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/instrumentation.rb#58
OpenTelemetry::Instrumentation::ActionMailer::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-action_mailer//lib/opentelemetry/instrumentation/action_mailer/version.rb#10
OpenTelemetry::Instrumentation::ActionMailer::VERSION = T.let(T.unsafe(nil), String)
