# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-helpers-sql` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-helpers-sql`.


# source://opentelemetry-helpers-sql//lib/opentelemetry/helpers.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-helpers-sql//lib/opentelemetry/helpers.rb#15
module OpenTelemetry::Helpers; end

# source://opentelemetry-helpers-sql//lib/opentelemetry/helpers/sql.rb#12
module OpenTelemetry::Helpers::Sql
  extend ::OpenTelemetry::Helpers::Sql

  # source://opentelemetry-helpers-sql//lib/opentelemetry/helpers/sql.rb#24
  def attributes(context = T.unsafe(nil)); end

  # source://opentelemetry-helpers-sql//lib/opentelemetry/helpers/sql.rb#34
  def context_with_attributes(attributes_hash, parent_context: T.unsafe(nil)); end

  # source://opentelemetry-helpers-sql//lib/opentelemetry/helpers/sql.rb#48
  def with_attributes(attributes_hash); end
end

# source://opentelemetry-helpers-sql//lib/opentelemetry/helpers/sql.rb#15
OpenTelemetry::Helpers::Sql::CURRENT_ATTRIBUTES_KEY = T.let(T.unsafe(nil), OpenTelemetry::Context::Key)

# source://opentelemetry-helpers-sql//lib/opentelemetry/helpers/sql/version.rb#10
OpenTelemetry::Helpers::Sql::VERSION = T.let(T.unsafe(nil), String)
