# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-registry` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-registry`.


# source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#7
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#8
module OpenTelemetry::Instrumentation
  extend ::OpenTelemetry::Instrumentation

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#13
class OpenTelemetry::Instrumentation::Registry
  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#14
  def initialize; end

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#44
  def install(instrumentation_names, instrumentation_config_map = T.unsafe(nil)); end

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#62
  def install_all(instrumentation_config_map = T.unsafe(nil)); end

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#31
  def lookup(instrumentation_name); end

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#20
  def register(instrumentation); end

  private

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#72
  def find_instrumentation(instrumentation_name); end

  # source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry.rb#77
  def install_instrumentation(instrumentation, config); end
end

# source://opentelemetry-registry//lib/opentelemetry/instrumentation/registry/version.rb#10
OpenTelemetry::Instrumentation::Registry::VERSION = T.let(T.unsafe(nil), String)
