# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-faraday` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-faraday`.


# source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday.rb#14
module OpenTelemetry::Instrumentation::Faraday; end

# source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/instrumentation.rb#12
class OpenTelemetry::Instrumentation::Faraday::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/instrumentation.rb#35
  def gem_version; end

  # source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/instrumentation.rb#44
  def register_tracer_middleware; end

  # source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/instrumentation.rb#39
  def require_dependencies; end

  # source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/instrumentation.rb#50
  def use_middleware_by_default; end
end

# source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/instrumentation.rb#13
OpenTelemetry::Instrumentation::Faraday::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-faraday//lib/opentelemetry/instrumentation/faraday/version.rb#10
OpenTelemetry::Instrumentation::Faraday::VERSION = T.let(T.unsafe(nil), String)
