# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `opentelemetry-instrumentation-sidekiq` gem.
# Please instead update this file by running `bin/tapioca gem opentelemetry-instrumentation-sidekiq`.


# source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation.rb#13
module OpenTelemetry
  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#36
  def error_handler; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def error_handler=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#44
  def handle_error(exception: T.unsafe(nil), message: T.unsafe(nil)); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#30
  def logger; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def logger=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#69
  def propagation; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#27
  def propagation=(_arg0); end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#64
  def tracer_provider; end

  # source://opentelemetry-api/1.5.0/lib/opentelemetry.rb#52
  def tracer_provider=(provider); end
end

# source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation.rb#18
module OpenTelemetry::Instrumentation
  # source://opentelemetry-registry/0.4.0/lib/opentelemetry/instrumentation.rb#21
  def registry; end
end

# source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq.rb#13
module OpenTelemetry::Instrumentation::Sidekiq; end

# source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#85
class OpenTelemetry::Instrumentation::Sidekiq::Instrumentation < ::OpenTelemetry::Instrumentation::Base
  private

  # source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#140
  def add_client_middleware; end

  # source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#148
  def add_server_middleware; end

  # source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#113
  def gem_version; end

  # source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#126
  def patch_on_startup; end

  # source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#117
  def require_dependencies; end
end

# source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/instrumentation.rb#86
OpenTelemetry::Instrumentation::Sidekiq::Instrumentation::MINIMUM_VERSION = T.let(T.unsafe(nil), Gem::Version)

# source://opentelemetry-instrumentation-sidekiq//lib/opentelemetry/instrumentation/sidekiq/version.rb#10
OpenTelemetry::Instrumentation::Sidekiq::VERSION = T.let(T.unsafe(nil), String)
