# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `orm_adapter` gem.
# Please instead update this file by running `bin/tapioca gem orm_adapter`.


# source://orm_adapter//lib/orm_adapter/base.rb#1
module OrmAdapter
  class << self
    # source://orm_adapter//lib/orm_adapter.rb#7
    def adapters; end
  end
end

# source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#4
class OrmAdapter::ActiveRecord < ::OrmAdapter::Base
  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#6
  def column_names; end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#31
  def create!(attributes = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#36
  def destroy(object); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#26
  def find_all(options = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#21
  def find_first(options = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#16
  def get(id); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#11
  def get!(id); end

  protected

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#53
  def conditions_to_fields(conditions); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#41
  def construct_relation(relation, options); end

  # source://orm_adapter//lib/orm_adapter/adapters/active_record.rb#73
  def order_clause(order); end
end

# source://orm_adapter//lib/orm_adapter/base.rb#2
class OrmAdapter::Base
  # source://orm_adapter//lib/orm_adapter/base.rb#17
  def initialize(klass); end

  # source://orm_adapter//lib/orm_adapter/base.rb#22
  def column_names; end

  # source://orm_adapter//lib/orm_adapter/base.rb#72
  def create!(attributes = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/base.rb#77
  def destroy(object); end

  # source://orm_adapter//lib/orm_adapter/base.rb#67
  def find_all(options = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/base.rb#61
  def find_first(options = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/base.rb#40
  def get(id); end

  # source://orm_adapter//lib/orm_adapter/base.rb#31
  def get!(id); end

  # source://orm_adapter//lib/orm_adapter/base.rb#3
  def klass; end

  protected

  # source://orm_adapter//lib/orm_adapter/base.rb#94
  def extract_conditions!(options = T.unsafe(nil)); end

  # source://orm_adapter//lib/orm_adapter/base.rb#104
  def normalize_order(order); end

  # source://orm_adapter//lib/orm_adapter/base.rb#83
  def valid_object?(object); end

  # source://orm_adapter//lib/orm_adapter/base.rb#87
  def wrap_key(key); end

  class << self
    # source://orm_adapter//lib/orm_adapter/base.rb#12
    def inherited(adapter); end
  end
end

# source://orm_adapter//lib/orm_adapter/base.rb#122
class OrmAdapter::NotSupportedError < ::NotImplementedError
  # source://orm_adapter//lib/orm_adapter/base.rb#123
  def to_s; end
end

# source://orm_adapter//lib/orm_adapter/to_adapter.rb#3
module OrmAdapter::ToAdapter
  # source://orm_adapter//lib/orm_adapter/to_adapter.rb#4
  def to_adapter; end
end

# source://orm_adapter//lib/orm_adapter/version.rb#2
OrmAdapter::VERSION = T.let(T.unsafe(nil), String)
