# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rack-proxy` gem.
# Please instead update this file by running `bin/tapioca gem rack-proxy`.


# source://rack-proxy//lib/net_http_hacked.rb#19
class Net::HTTP < ::Net::Protocol
  # source://rack-proxy//lib/net_http_hacked.rb#49
  def begin_request_hacked(req); end

  # source://rack-proxy//lib/net_http_hacked.rb#60
  def end_request_hacked; end
end

# source://rack-proxy//lib/net_http_hacked.rb#67
class Net::HTTPResponse
  # source://rack-proxy//lib/net_http_hacked.rb#81
  def begin_reading_body_hacked(sock, reqmethodallowbody); end

  # source://rack-proxy//lib/net_http_hacked.rb#86
  def end_reading_body_hacked; end
end

# source://rack-proxy//lib/rack/http_streaming_response.rb#4
module Rack
  class << self
    # source://rack/3.2.0/lib/rack/version.rb#14
    def release; end
  end
end

# source://rack-proxy//lib/rack/http_streaming_response.rb#6
class Rack::HttpStreamingResponse
  # source://rack-proxy//lib/rack/http_streaming_response.rb#15
  def initialize(request, host, port = T.unsafe(nil)); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#19
  def body; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def cert; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def cert=(_arg0); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#23
  def code; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#36
  def each(&block); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#31
  def headers; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def key; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def key=(_arg0); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def read_timeout; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def read_timeout=(_arg0); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def ssl_version; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def ssl_version=(_arg0); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#23
  def status; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#44
  def to_s; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def use_ssl; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def use_ssl=(_arg0); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def verify_mode; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#13
  def verify_mode=(_arg0); end

  protected

  # source://rack-proxy//lib/rack/http_streaming_response.rb#51
  def response; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#56
  def session; end

  private

  # source://rack-proxy//lib/rack/http_streaming_response.rb#74
  def close_connection; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#72
  def connection_closed; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#72
  def connection_closed=(_arg0); end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#70
  def host; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#70
  def port; end

  # source://rack-proxy//lib/rack/http_streaming_response.rb#70
  def request; end
end

# source://rack-proxy//lib/rack/http_streaming_response.rb#7
Rack::HttpStreamingResponse::STATUSES_WITH_NO_ENTITY_BODY = T.let(T.unsafe(nil), Hash)

# source://rack-proxy//lib/rack/proxy.rb#7
class Rack::Proxy
  # source://rack-proxy//lib/rack/proxy.rb#63
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil)); end

  # source://rack-proxy//lib/rack/proxy.rb#86
  def call(env); end

  # source://rack-proxy//lib/rack/proxy.rb#91
  def rewrite_env(env); end

  # source://rack-proxy//lib/rack/proxy.rb#96
  def rewrite_response(triplet); end

  protected

  # source://rack-proxy//lib/rack/proxy.rb#102
  def perform_request(env); end

  class << self
    # source://rack-proxy//lib/rack/proxy.rb#41
    def build_header_hash(pairs); end

    # source://rack-proxy//lib/rack/proxy.rb#22
    def extract_http_request_headers(env); end

    # source://rack-proxy//lib/rack/proxy.rb#34
    def normalize_headers(headers); end

    protected

    # source://rack-proxy//lib/rack/proxy.rb#53
    def reconstruct_header_name(name); end

    # source://rack-proxy//lib/rack/proxy.rb#57
    def titleize(str); end
  end
end

# source://rack-proxy//lib/rack/proxy.rb#10
Rack::Proxy::HOP_BY_HOP_HEADERS = T.let(T.unsafe(nil), Hash)

# source://rack-proxy//lib/rack/proxy.rb#8
Rack::Proxy::VERSION = T.let(T.unsafe(nil), String)
