# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `railties` gem.
# Please instead update this file by running `bin/tapioca gem railties`.


# source://railties//lib/rails/gem_version.rb#3
module Rails
  extend ::ActiveSupport::Autoload
  extend ::ActiveSupport::Benchmarkable

  class << self
    # source://railties//lib/rails.rb#44
    def app_class; end

    # source://railties//lib/rails.rb#44
    def app_class=(_arg0); end

    # source://railties//lib/rails.rb#45
    def application; end

    # source://railties//lib/rails.rb#43
    def application=(_arg0); end

    # source://railties//lib/rails.rb#126
    def autoloaders; end

    # source://railties//lib/rails.rb#56
    def backtrace_cleaner; end

    # source://railties//lib/rails.rb#44
    def cache; end

    # source://railties//lib/rails.rb#44
    def cache=(_arg0); end

    # source://railties//lib/rails.rb#52
    def configuration; end

    # source://railties//lib/rails/deprecator.rb#4
    def deprecator; end

    # source://railties//lib/rails.rb#75
    def env; end

    # source://railties//lib/rails.rb#82
    def env=(environment); end

    # source://railties//lib/rails.rb#93
    def error; end

    # source://railties//lib/rails/gem_version.rb#5
    def gem_version; end

    # source://railties//lib/rails.rb#106
    def groups(*groups); end

    # source://railties//lib/rails.rb#49
    def initialize!(*_arg0, **_arg1, &_arg2); end

    # source://railties//lib/rails.rb#49
    def initialized?(*_arg0, **_arg1, &_arg2); end

    # source://railties//lib/rails.rb#44
    def logger; end

    # source://railties//lib/rails.rb#44
    def logger=(_arg0); end

    # source://railties//lib/rails.rb#122
    def public_path; end

    # source://railties//lib/rails.rb#65
    def root; end

    # source://railties//lib/rails/version.rb#7
    def version; end
  end
end

# source://railties//lib/rails/application.rb#62
class Rails::Application < ::Rails::Engine
  # source://railties//lib/rails/application.rb#109
  def initialize(initial_variable_values = T.unsafe(nil), &block); end

  # source://railties//lib/rails/application.rb#100
  def assets; end

  # source://railties//lib/rails/application.rb#100
  def assets=(_arg0); end

  # source://railties//lib/rails/application.rb#102
  def autoloaders; end

  # source://railties//lib/rails/engine.rb#516
  def build_middleware_stack; end

  # source://railties//lib/rails/application.rb#451
  def config; end

  # source://railties//lib/rails/application.rb#455
  def config=(_arg0); end

  # source://railties//lib/rails/application.rb#288
  def config_for(name, env: T.unsafe(nil)); end

  # source://railties//lib/rails/application.rb#371
  def console(&blk); end

  # source://railties//lib/rails/application.rb#495
  def credentials; end

  # source://railties//lib/rails/application.rb#456
  def credentials=(_arg0); end

  # source://railties//lib/rails/application.rb#104
  def default_url_options(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/application.rb#104
  def default_url_options=(arg); end

  # source://railties//lib/rails/application.rb#244
  def deprecators; end

  # source://railties//lib/rails/application.rb#553
  def eager_load!; end

  # source://railties//lib/rails/application.rb#514
  def encrypted(path, key_path: T.unsafe(nil), env_key: T.unsafe(nil)); end

  # source://railties//lib/rails/application.rb#317
  def env_config; end

  # source://railties//lib/rails/application.rb#102
  def executor; end

  # source://railties//lib/rails/application.rb#377
  def generators(&blk); end

  # source://railties//lib/rails/application.rb#527
  def helpers_paths; end

  # source://railties//lib/rails/application.rb#438
  def initialize!(group = T.unsafe(nil)); end

  # source://railties//lib/rails/application.rb#134
  def initialized?; end

  # source://railties//lib/rails/application.rb#359
  def initializer(name, opts = T.unsafe(nil), &block); end

  # source://railties//lib/rails/application.rb#445
  def initializers; end

  # source://railties//lib/rails/application.rb#388
  def isolate_namespace(mod); end

  # source://railties//lib/rails/application.rb#172
  def key_generator(secret_key_base = T.unsafe(nil)); end

  # source://railties//lib/rails/application.rb#547
  def load_generators(app = T.unsafe(nil)); end

  # source://railties//lib/rails/application.rb#236
  def message_verifier(verifier_name); end

  # source://railties//lib/rails/application.rb#208
  def message_verifiers; end

  # source://railties//lib/rails/application.rb#543
  def migration_railties; end

  # source://railties//lib/rails/application.rb#141
  def name; end

  # source://railties//lib/rails/application.rb#352
  def rake_tasks(&block); end

  # source://railties//lib/rails/application.rb#160
  def reload_routes!; end

  # source://railties//lib/rails/application.rb#164
  def reload_routes_unless_loaded; end

  # source://railties//lib/rails/application.rb#102
  def reloader; end

  # source://railties//lib/rails/application.rb#102
  def reloaders; end

  # source://railties//lib/rails/application.rb#414
  def require_environment!; end

  # source://railties//lib/rails/application.rb#419
  def routes_reloader; end

  # source://railties//lib/rails/application.rb#145
  def run_load_hooks!; end

  # source://railties//lib/rails/application.rb#365
  def runner(&blk); end

  # source://railties//lib/rails/application.rb#100
  def sandbox; end

  # source://railties//lib/rails/application.rb#100
  def sandbox=(_arg0); end

  # source://railties//lib/rails/application.rb#100
  def sandbox?; end

  # source://railties//lib/rails/application.rb#477
  def secret_key_base; end

  # source://railties//lib/rails/application.rb#383
  def server(&blk); end

  # source://railties//lib/rails/application.rb#523
  def to_app; end

  # source://railties//lib/rails/application.rb#426
  def watchable_args; end

  protected

  # source://railties//lib/rails/application.rb#626
  def default_middleware_stack; end

  # source://railties//lib/rails/application.rb#631
  def ensure_generator_templates_added; end

  # source://railties//lib/rails/application.rb#592
  def ordered_railties; end

  # source://railties//lib/rails/application.rb#614
  def railties_initializers(current); end

  # source://railties//lib/rails/application.rb#581
  def run_console_blocks(app); end

  # source://railties//lib/rails/application.rb#571
  def run_generators_blocks(app); end

  # source://railties//lib/rails/application.rb#576
  def run_runner_blocks(app); end

  # source://railties//lib/rails/application.rb#586
  def run_server_blocks(app); end

  # source://railties//lib/rails/application.rb#560
  def run_tasks_blocks(app); end

  private

  # source://railties//lib/rails/application.rb#644
  def build_middleware; end

  # source://railties//lib/rails/application.rb#637
  def build_request(env); end

  # source://railties//lib/rails/application.rb#648
  def coerce_same_site_protection(protection); end

  # source://railties//lib/rails/application.rb#652
  def filter_parameters; end

  class << self
    # source://railties//lib/rails/application.rb#407
    def add_lib_to_load_path!(root); end

    # source://railties//lib/rails/application.rb#84
    def create(initial_variable_values = T.unsafe(nil), &block); end

    # source://railties//lib/rails/application.rb#88
    def find_root(from); end

    # source://railties//lib/rails/application.rb#71
    def inherited(base); end

    # source://railties//lib/rails/application.rb#80
    def instance; end

    def new(*_arg0); end
  end
end

# source://railties//lib/rails/application/bootstrap.rb#10
module Rails::Application::Bootstrap
  include ::Rails::Initializable
  extend ::Rails::Initializable::ClassMethods
end

# source://railties//lib/rails/application/configuration.rb#13
class Rails::Application::Configuration < ::Rails::Engine::Configuration
  # source://railties//lib/rails/application/configuration.rb#30
  def initialize(*_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def add_autoload_paths_to_load_path; end

  # source://railties//lib/rails/application/configuration.rb#14
  def add_autoload_paths_to_load_path=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def allow_concurrency; end

  # source://railties//lib/rails/application/configuration.rb#14
  def allow_concurrency=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#563
  def annotations; end

  # source://railties//lib/rails/application/configuration.rb#28
  def api_only; end

  # source://railties//lib/rails/application/configuration.rb#376
  def api_only=(value); end

  # source://railties//lib/rails/application/configuration.rb#14
  def asset_host; end

  # source://railties//lib/rails/application/configuration.rb#14
  def asset_host=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def assume_ssl; end

  # source://railties//lib/rails/application/configuration.rb#14
  def assume_ssl=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def autoflush_log; end

  # source://railties//lib/rails/application/configuration.rb#14
  def autoflush_log=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#471
  def autoload_lib(ignore:); end

  # source://railties//lib/rails/application/configuration.rb#483
  def autoload_lib_once(ignore:); end

  # source://railties//lib/rails/application/configuration.rb#14
  def beginning_of_week; end

  # source://railties//lib/rails/application/configuration.rb#14
  def beginning_of_week=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#388
  def broadcast_log_level; end

  # source://railties//lib/rails/application/configuration.rb#14
  def cache_classes; end

  # source://railties//lib/rails/application/configuration.rb#14
  def cache_classes=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def cache_store; end

  # source://railties//lib/rails/application/configuration.rb#14
  def cache_store=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#495
  def colorize_logging; end

  # source://railties//lib/rails/application/configuration.rb#499
  def colorize_logging=(val); end

  # source://railties//lib/rails/application/configuration.rb#14
  def consider_all_requests_local; end

  # source://railties//lib/rails/application/configuration.rb#14
  def consider_all_requests_local=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def console; end

  # source://railties//lib/rails/application/configuration.rb#14
  def console=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#568
  def content_security_policy(&block); end

  # source://railties//lib/rails/application/configuration.rb#14
  def content_security_policy_nonce_directives; end

  # source://railties//lib/rails/application/configuration.rb#14
  def content_security_policy_nonce_directives=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def content_security_policy_nonce_generator; end

  # source://railties//lib/rails/application/configuration.rb#14
  def content_security_policy_nonce_generator=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def content_security_policy_report_only; end

  # source://railties//lib/rails/application/configuration.rb#14
  def content_security_policy_report_only=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def credentials; end

  # source://railties//lib/rails/application/configuration.rb#14
  def credentials=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#434
  def database_configuration; end

  # source://railties//lib/rails/application/configuration.rb#390
  def debug_exception_response_format; end

  # source://railties//lib/rails/application/configuration.rb#394
  def debug_exception_response_format=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#585
  def default_log_file; end

  # source://railties//lib/rails/application/configuration.rb#14
  def disable_sandbox; end

  # source://railties//lib/rails/application/configuration.rb#14
  def disable_sandbox=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def dom_testing_default_html_version; end

  # source://railties//lib/rails/application/configuration.rb#14
  def dom_testing_default_html_version=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def eager_load; end

  # source://railties//lib/rails/application/configuration.rb#14
  def eager_load=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#360
  def enable_reloading; end

  # source://railties//lib/rails/application/configuration.rb#364
  def enable_reloading=(value); end

  # source://railties//lib/rails/application/configuration.rb#28
  def encoding; end

  # source://railties//lib/rails/application/configuration.rb#368
  def encoding=(value); end

  # source://railties//lib/rails/application/configuration.rb#14
  def exceptions_app; end

  # source://railties//lib/rails/application/configuration.rb#14
  def exceptions_app=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def file_watcher; end

  # source://railties//lib/rails/application/configuration.rb#14
  def file_watcher=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def filter_parameters; end

  # source://railties//lib/rails/application/configuration.rb#14
  def filter_parameters=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def filter_redirect; end

  # source://railties//lib/rails/application/configuration.rb#14
  def filter_redirect=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def force_ssl; end

  # source://railties//lib/rails/application/configuration.rb#14
  def force_ssl=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def helpers_paths; end

  # source://railties//lib/rails/application/configuration.rb#14
  def helpers_paths=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def host_authorization; end

  # source://railties//lib/rails/application/configuration.rb#14
  def host_authorization=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def hosts; end

  # source://railties//lib/rails/application/configuration.rb#14
  def hosts=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#597
  def inspect; end

  # source://railties//lib/rails/application/configuration.rb#416
  def load_database_yaml; end

  # source://railties//lib/rails/application/configuration.rb#92
  def load_defaults(target_version); end

  # source://railties//lib/rails/application/configuration.rb#28
  def loaded_config_version; end

  # source://railties//lib/rails/application/configuration.rb#14
  def log_file_size; end

  # source://railties//lib/rails/application/configuration.rb#14
  def log_file_size=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def log_formatter; end

  # source://railties//lib/rails/application/configuration.rb#14
  def log_formatter=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#28
  def log_level; end

  # source://railties//lib/rails/application/configuration.rb#383
  def log_level=(level); end

  # source://railties//lib/rails/application/configuration.rb#14
  def log_tags; end

  # source://railties//lib/rails/application/configuration.rb#14
  def log_tags=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def logger; end

  # source://railties//lib/rails/application/configuration.rb#14
  def logger=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#396
  def paths; end

  # source://railties//lib/rails/application/configuration.rb#577
  def permissions_policy(&block); end

  # source://railties//lib/rails/application/configuration.rb#14
  def precompile_filter_parameters; end

  # source://railties//lib/rails/application/configuration.rb#14
  def precompile_filter_parameters=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def public_file_server; end

  # source://railties//lib/rails/application/configuration.rb#14
  def public_file_server=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def railties_order; end

  # source://railties//lib/rails/application/configuration.rb#14
  def railties_order=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def rake_eager_load; end

  # source://railties//lib/rails/application/configuration.rb#14
  def rake_eager_load=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def relative_url_root; end

  # source://railties//lib/rails/application/configuration.rb#14
  def relative_url_root=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def reload_classes_only_on_change; end

  # source://railties//lib/rails/application/configuration.rb#14
  def reload_classes_only_on_change=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#356
  def reloading_enabled?; end

  # source://railties//lib/rails/application/configuration.rb#14
  def require_master_key; end

  # source://railties//lib/rails/application/configuration.rb#14
  def require_master_key=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def sandbox_by_default; end

  # source://railties//lib/rails/application/configuration.rb#14
  def sandbox_by_default=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#504
  def secret_key_base; end

  # source://railties//lib/rails/application/configuration.rb#516
  def secret_key_base=(new_secret_key_base); end

  # source://railties//lib/rails/application/configuration.rb#14
  def server_timing; end

  # source://railties//lib/rails/application/configuration.rb#14
  def server_timing=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def session_options; end

  # source://railties//lib/rails/application/configuration.rb#14
  def session_options=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#543
  def session_store(new_session_store = T.unsafe(nil), **options); end

  # source://railties//lib/rails/application/configuration.rb#559
  def session_store?; end

  # source://railties//lib/rails/application/configuration.rb#14
  def silence_healthcheck_path; end

  # source://railties//lib/rails/application/configuration.rb#14
  def silence_healthcheck_path=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def ssl_options; end

  # source://railties//lib/rails/application/configuration.rb#14
  def ssl_options=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def time_zone; end

  # source://railties//lib/rails/application/configuration.rb#14
  def time_zone=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def x; end

  # source://railties//lib/rails/application/configuration.rb#14
  def x=(_arg0); end

  # source://railties//lib/rails/application/configuration.rb#14
  def yjit; end

  # source://railties//lib/rails/application/configuration.rb#14
  def yjit=(_arg0); end

  private

  # source://railties//lib/rails/application/configuration.rb#624
  def credentials_defaults; end

  # source://railties//lib/rails/application/configuration.rb#634
  def generate_local_secret; end
end

# source://railties//lib/rails/application/configuration.rb#601
class Rails::Application::Configuration::Custom
  # source://railties//lib/rails/application/configuration.rb#602
  def initialize; end

  # source://railties//lib/rails/application/configuration.rb#606
  def method_missing(method, *args); end

  private

  # source://railties//lib/rails/application/configuration.rb#618
  def respond_to_missing?(symbol, _); end
end

# source://railties//lib/rails/application/default_middleware_stack.rb#5
class Rails::Application::DefaultMiddlewareStack
  # source://railties//lib/rails/application/default_middleware_stack.rb#8
  def initialize(app, config, paths); end

  # source://railties//lib/rails/application/default_middleware_stack.rb#6
  def app; end

  # source://railties//lib/rails/application/default_middleware_stack.rb#14
  def build_stack; end

  # source://railties//lib/rails/application/default_middleware_stack.rb#6
  def config; end

  # source://railties//lib/rails/application/default_middleware_stack.rb#6
  def paths; end

  private

  # source://railties//lib/rails/application/default_middleware_stack.rb#113
  def load_rack_cache; end

  # source://railties//lib/rails/application/default_middleware_stack.rb#135
  def show_exceptions_app; end
end

# source://railties//lib/rails/application/finisher.rb#10
module Rails::Application::Finisher
  include ::Rails::Initializable
  extend ::Rails::Initializable::ClassMethods
end

# source://railties//lib/rails/application/finisher.rb#110
module Rails::Application::Finisher::InterlockHook
  class << self
    # source://railties//lib/rails/application/finisher.rb#115
    def complete(_state); end

    # source://railties//lib/rails/application/finisher.rb#111
    def run; end
  end
end

# source://railties//lib/rails/application/finisher.rb#96
class Rails::Application::Finisher::MonitorHook
  # source://railties//lib/rails/application/finisher.rb#97
  def initialize(monitor = T.unsafe(nil)); end

  # source://railties//lib/rails/application/finisher.rb#105
  def complete(_state); end

  # source://railties//lib/rails/application/finisher.rb#101
  def run; end
end

# source://railties//lib/rails/application.rb#106
Rails::Application::INITIAL_VARIABLES = T.let(T.unsafe(nil), Array)

# source://railties//lib/rails/application/routes_reloader.rb#7
class Rails::Application::RoutesReloader
  include ::ActiveSupport::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker

  # source://railties//lib/rails/application/routes_reloader.rb#15
  def initialize; end

  # source://activesupport/8.0.2/lib/active_support/callbacks.rb#69
  def __callbacks; end

  # source://railties//lib/rails/application/routes_reloader.rb#11
  def eager_load; end

  # source://railties//lib/rails/application/routes_reloader.rb#11
  def eager_load=(_arg0); end

  # source://railties//lib/rails/application/routes_reloader.rb#32
  def execute; end

  # source://railties//lib/rails/application/routes_reloader.rb#13
  def execute_if_updated(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/application/routes_reloader.rb#37
  def execute_unless_loaded; end

  # source://railties//lib/rails/application/routes_reloader.rb#10
  def external_routes; end

  # source://railties//lib/rails/application/routes_reloader.rb#10
  def loaded; end

  # source://railties//lib/rails/application/routes_reloader.rb#10
  def paths; end

  # source://railties//lib/rails/application/routes_reloader.rb#23
  def reload!; end

  # source://railties//lib/rails/application/routes_reloader.rb#10
  def route_sets; end

  # source://railties//lib/rails/application/routes_reloader.rb#12
  def run_after_load_paths=(_arg0); end

  # source://railties//lib/rails/application/routes_reloader.rb#13
  def updated?(*_arg0, **_arg1, &_arg2); end

  private

  # source://railties//lib/rails/application/routes_reloader.rb#56
  def clear!; end

  # source://railties//lib/rails/application/routes_reloader.rb#72
  def finalize!; end

  # source://railties//lib/rails/application/routes_reloader.rb#63
  def load_paths; end

  # source://railties//lib/rails/application/routes_reloader.rb#76
  def revert; end

  # source://railties//lib/rails/application/routes_reloader.rb#68
  def run_after_load_paths; end

  # source://railties//lib/rails/application/routes_reloader.rb#46
  def updater; end

  class << self
    # source://activesupport/8.0.2/lib/active_support/callbacks.rb#69
    def __callbacks; end

    # source://activesupport/8.0.2/lib/active_support/callbacks.rb#69
    def __callbacks=(value); end

    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://railties//lib/rails/application_controller.rb#3
class Rails::ApplicationController < ::ActionController::Base
  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  # source://railties//lib/rails/application_controller.rb#25
  def disable_content_security_policy_nonce!; end

  # source://railties//lib/rails/application_controller.rb#21
  def local_request?; end

  # source://railties//lib/rails/application_controller.rb#15
  def require_local!; end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout_conditions; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout_conditions=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

# source://railties//lib/rails/autoloaders.rb#4
class Rails::Autoloaders
  include ::Enumerable

  # source://railties//lib/rails/autoloaders.rb#11
  def initialize; end

  # source://railties//lib/rails/autoloaders.rb#31
  def each; end

  # source://railties//lib/rails/autoloaders.rb#40
  def log!; end

  # source://railties//lib/rails/autoloaders.rb#36
  def logger=(logger); end

  # source://railties//lib/rails/autoloaders.rb#9
  def main; end

  # source://railties//lib/rails/autoloaders.rb#9
  def once; end

  # source://railties//lib/rails/autoloaders.rb#44
  def zeitwerk_enabled?; end
end

# source://railties//lib/rails/autoloaders/inflector.rb#7
module Rails::Autoloaders::Inflector
  class << self
    # source://railties//lib/rails/autoloaders/inflector.rb#12
    def camelize(basename, _abspath); end

    # source://railties//lib/rails/autoloaders/inflector.rb#16
    def inflect(overrides); end
  end
end

# source://railties//lib/rails/backtrace_cleaner.rb#7
class Rails::BacktraceCleaner < ::ActiveSupport::BacktraceCleaner
  # source://railties//lib/rails/backtrace_cleaner.rb#11
  def initialize; end

  # source://railties//lib/rails/backtrace_cleaner.rb#29
  def clean(backtrace, kind = T.unsafe(nil)); end

  # source://railties//lib/rails/backtrace_cleaner.rb#36
  def clean_frame(frame, kind = T.unsafe(nil)); end

  # source://railties//lib/rails/backtrace_cleaner.rb#29
  def filter(backtrace, kind = T.unsafe(nil)); end
end

# source://railties//lib/rails/backtrace_cleaner.rb#8
Rails::BacktraceCleaner::APP_DIRS_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://railties//lib/rails/backtrace_cleaner.rb#9
Rails::BacktraceCleaner::RENDER_TEMPLATE_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://railties//lib/rails/code_statistics.rb#7
class Rails::CodeStatistics
  # source://railties//lib/rails/code_statistics.rb#60
  def initialize(*pairs); end

  # source://railties//lib/rails/code_statistics.rb#45
  def directories; end

  # source://railties//lib/rails/code_statistics.rb#45
  def directories=(_arg0); end

  # source://railties//lib/rails/code_statistics.rb#45
  def directories?; end

  # source://railties//lib/rails/code_statistics.rb#46
  def test_types; end

  # source://railties//lib/rails/code_statistics.rb#46
  def test_types=(_arg0); end

  # source://railties//lib/rails/code_statistics.rb#46
  def test_types?; end

  # source://railties//lib/rails/code_statistics.rb#66
  def to_s; end

  private

  # source://railties//lib/rails/code_statistics.rb#106
  def calculate_code; end

  # source://railties//lib/rails/code_statistics.rb#84
  def calculate_directory_statistics(directory, pattern = T.unsafe(nil)); end

  # source://railties//lib/rails/code_statistics.rb#80
  def calculate_statistics; end

  # source://railties//lib/rails/code_statistics.rb#112
  def calculate_tests; end

  # source://railties//lib/rails/code_statistics.rb#100
  def calculate_total; end

  # source://railties//lib/rails/code_statistics.rb#151
  def print_code_test_stats; end

  # source://railties//lib/rails/code_statistics.rb#122
  def print_header; end

  # source://railties//lib/rails/code_statistics.rb#140
  def print_line(name, statistics); end

  # source://railties//lib/rails/code_statistics.rb#132
  def print_splitter; end

  # source://railties//lib/rails/code_statistics.rb#118
  def width_for(label); end

  class << self
    # source://railties//lib/rails/code_statistics.rb#45
    def directories; end

    # source://railties//lib/rails/code_statistics.rb#45
    def directories=(value); end

    # source://railties//lib/rails/code_statistics.rb#45
    def directories?; end

    # source://railties//lib/rails/code_statistics.rb#55
    def register_directory(label, path, test_directory: T.unsafe(nil)); end

    # source://railties//lib/rails/code_statistics.rb#46
    def test_types; end

    # source://railties//lib/rails/code_statistics.rb#46
    def test_types=(value); end

    # source://railties//lib/rails/code_statistics.rb#46
    def test_types?; end

    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_directories; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_directories=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_test_types; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_test_types=(new_value); end
  end
end

# source://railties//lib/rails/code_statistics.rb#8
Rails::CodeStatistics::DIRECTORIES = T.let(T.unsafe(nil), Array)

# source://railties//lib/rails/code_statistics.rb#43
Rails::CodeStatistics::HEADERS = T.let(T.unsafe(nil), Hash)

# source://railties//lib/rails/code_statistics.rb#33
Rails::CodeStatistics::TEST_TYPES = T.let(T.unsafe(nil), Array)

# source://railties//lib/rails/code_statistics_calculator.rb#4
class Rails::CodeStatisticsCalculator
  # source://railties//lib/rails/code_statistics_calculator.rb#42
  def initialize(lines = T.unsafe(nil), code_lines = T.unsafe(nil), classes = T.unsafe(nil), methods = T.unsafe(nil)); end

  # source://railties//lib/rails/code_statistics_calculator.rb#49
  def add(code_statistics_calculator); end

  # source://railties//lib/rails/code_statistics_calculator.rb#56
  def add_by_file_path(file_path); end

  # source://railties//lib/rails/code_statistics_calculator.rb#62
  def add_by_io(io, file_type); end

  # source://railties//lib/rails/code_statistics_calculator.rb#5
  def classes; end

  # source://railties//lib/rails/code_statistics_calculator.rb#5
  def code_lines; end

  # source://railties//lib/rails/code_statistics_calculator.rb#5
  def lines; end

  # source://railties//lib/rails/code_statistics_calculator.rb#5
  def methods; end

  private

  # source://railties//lib/rails/code_statistics_calculator.rb#91
  def file_type(file_path); end
end

# source://railties//lib/rails/code_statistics_calculator.rb#7
Rails::CodeStatisticsCalculator::PATTERNS = T.let(T.unsafe(nil), Hash)

# source://railties//lib/rails/configuration.rb#9
module Rails::Configuration; end

# source://railties//lib/rails/configuration.rb#104
class Rails::Configuration::Generators
  # source://railties//lib/rails/configuration.rb#108
  def initialize; end

  # source://railties//lib/rails/configuration.rb#130
  def after_generate(&block); end

  # source://railties//lib/rails/configuration.rb#106
  def after_generate_callbacks; end

  # source://railties//lib/rails/configuration.rb#105
  def aliases; end

  # source://railties//lib/rails/configuration.rb#105
  def aliases=(_arg0); end

  # source://railties//lib/rails/configuration.rb#105
  def api_only; end

  # source://railties//lib/rails/configuration.rb#105
  def api_only=(_arg0); end

  # source://railties//lib/rails/configuration.rb#134
  def apply_rubocop_autocorrect_after_generate!; end

  # source://railties//lib/rails/configuration.rb#105
  def colorize_logging; end

  # source://railties//lib/rails/configuration.rb#105
  def colorize_logging=(_arg0); end

  # source://railties//lib/rails/configuration.rb#105
  def fallbacks; end

  # source://railties//lib/rails/configuration.rb#105
  def fallbacks=(_arg0); end

  # source://railties//lib/rails/configuration.rb#106
  def hidden_namespaces; end

  # source://railties//lib/rails/configuration.rb#126
  def hide_namespace(namespace); end

  # source://railties//lib/rails/configuration.rb#143
  def method_missing(method, *args); end

  # source://railties//lib/rails/configuration.rb#105
  def options; end

  # source://railties//lib/rails/configuration.rb#105
  def options=(_arg0); end

  # source://railties//lib/rails/configuration.rb#105
  def templates; end

  # source://railties//lib/rails/configuration.rb#105
  def templates=(_arg0); end

  private

  # source://railties//lib/rails/configuration.rb#119
  def initialize_copy(source); end
end

# source://railties//lib/rails/configuration.rb#46
class Rails::Configuration::MiddlewareStackProxy
  # source://railties//lib/rails/configuration.rb#47
  def initialize(operations = T.unsafe(nil), delete_operations = T.unsafe(nil)); end

  # source://railties//lib/rails/configuration.rb#96
  def +(other); end

  # source://railties//lib/rails/configuration.rb#70
  def delete(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#52
  def insert(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#58
  def insert_after(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#52
  def insert_before(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#88
  def merge_into(other); end

  # source://railties//lib/rails/configuration.rb#74
  def move(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#80
  def move_after(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#74
  def move_before(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#62
  def swap(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#84
  def unshift(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/configuration.rb#66
  def use(*_arg0, **_arg1, &_arg2); end

  protected

  # source://railties//lib/rails/configuration.rb#101
  def delete_operations; end

  # source://railties//lib/rails/configuration.rb#101
  def operations; end
end

# source://railties//lib/rails/engine/railties.rb#4
class Rails::Engine < ::Rails::Railtie
  include ::ActiveSupport::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods

  # source://railties//lib/rails/engine.rb#440
  def initialize; end

  # source://activesupport/8.0.2/lib/active_support/callbacks.rb#69
  def __callbacks; end

  # source://activesupport/8.0.2/lib/active_support/callbacks.rb#924
  def _load_seed_callbacks; end

  # source://activesupport/8.0.2/lib/active_support/callbacks.rb#912
  def _run_load_seed_callbacks(&block); end

  # source://railties//lib/rails/engine.rb#516
  def app; end

  # source://railties//lib/rails/engine.rb#533
  def call(env); end

  # source://railties//lib/rails/engine.rb#552
  def config; end

  # source://railties//lib/rails/engine.rb#490
  def eager_load!; end

  # source://railties//lib/rails/engine.rb#528
  def endpoint; end

  # source://railties//lib/rails/engine.rb#438
  def engine_name(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/engine.rb#539
  def env_config; end

  # source://railties//lib/rails/engine.rb#500
  def helpers; end

  # source://railties//lib/rails/engine.rb#511
  def helpers_paths; end

  # source://railties//lib/rails/engine.rb#438
  def isolated?(&_arg0); end

  # source://railties//lib/rails/engine.rb#454
  def load_console(app = T.unsafe(nil)); end

  # source://railties//lib/rails/engine.rb#476
  def load_generators(app = T.unsafe(nil)); end

  # source://railties//lib/rails/engine.rb#461
  def load_runner(app = T.unsafe(nil)); end

  # source://railties//lib/rails/engine.rb#560
  def load_seed; end

  # source://railties//lib/rails/engine.rb#485
  def load_server(app = T.unsafe(nil)); end

  # source://railties//lib/rails/engine.rb#468
  def load_tasks(app = T.unsafe(nil)); end

  # source://railties//lib/rails/engine.rb#437
  def middleware(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/engine.rb#437
  def paths(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/engine.rb#495
  def railties; end

  # source://railties//lib/rails/engine.rb#437
  def root(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/engine.rb#545
  def routes(&block); end

  # source://railties//lib/rails/engine.rb#680
  def routes?; end

  protected

  # source://railties//lib/rails/engine.rb#685
  def run_tasks_blocks(*_arg0); end

  private

  # source://railties//lib/rails/engine.rb#717
  def _all_autoload_once_paths; end

  # source://railties//lib/rails/engine.rb#721
  def _all_autoload_paths; end

  # source://railties//lib/rails/engine.rb#730
  def _all_load_paths(add_autoload_paths_to_load_path); end

  # source://railties//lib/rails/engine.rb#755
  def build_middleware; end

  # source://railties//lib/rails/engine.rb#747
  def build_request(env); end

  # source://railties//lib/rails/engine.rb#713
  def default_middleware_stack; end

  # source://railties//lib/rails/engine.rb#741
  def fixtures_in_root_and_not_in_vendor_or_dot_dir?(fixtures); end

  # source://railties//lib/rails/engine.rb#697
  def has_migrations?; end

  # source://railties//lib/rails/engine.rb#691
  def load_config_initializer(initializer); end

  class << self
    # source://activesupport/8.0.2/lib/active_support/callbacks.rb#69
    def __callbacks; end

    # source://activesupport/8.0.2/lib/active_support/callbacks.rb#69
    def __callbacks=(value); end

    # source://activesupport/8.0.2/lib/active_support/callbacks.rb#916
    def _load_seed_callbacks; end

    # source://activesupport/8.0.2/lib/active_support/callbacks.rb#920
    def _load_seed_callbacks=(value); end

    # source://railties//lib/rails/engine.rb#354
    def called_from; end

    # source://railties//lib/rails/engine.rb#354
    def called_from=(_arg0); end

    # source://railties//lib/rails/engine.rb#359
    def eager_load!(*_arg0, **_arg1, &_arg2); end

    # source://railties//lib/rails/engine.rb#379
    def endpoint(endpoint = T.unsafe(nil)); end

    # source://railties//lib/rails/railtie.rb#176
    def engine_name(name = T.unsafe(nil)); end

    # source://railties//lib/rails/engine.rb#424
    def find(path); end

    # source://railties//lib/rails/engine.rb#375
    def find_root(from); end

    # source://railties//lib/rails/engine.rb#701
    def find_root_with_flag(flag, root_path, default = T.unsafe(nil)); end

    # source://railties//lib/rails/engine.rb#361
    def inherited(base); end

    # source://railties//lib/rails/engine.rb#385
    def isolate_namespace(mod); end

    # source://railties//lib/rails/engine.rb#354
    def isolated; end

    # source://railties//lib/rails/engine.rb#354
    def isolated=(_arg0); end

    # source://railties//lib/rails/engine.rb#354
    def isolated?; end

    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end
  end
end

# source://railties//lib/rails/engine/configuration.rb#7
class Rails::Engine::Configuration < ::Rails::Railtie::Configuration
  # source://railties//lib/rails/engine/configuration.rb#41
  def initialize(root = T.unsafe(nil)); end

  # source://railties//lib/rails/engine/configuration.rb#127
  def all_autoload_once_paths; end

  # source://railties//lib/rails/engine/configuration.rb#121
  def all_autoload_paths; end

  # source://railties//lib/rails/engine/configuration.rb#133
  def all_eager_load_paths; end

  # source://railties//lib/rails/engine/configuration.rb#29
  def autoload_once_paths; end

  # source://railties//lib/rails/engine/configuration.rb#10
  def autoload_once_paths=(_arg0); end

  # source://railties//lib/rails/engine/configuration.rb#20
  def autoload_paths; end

  # source://railties//lib/rails/engine/configuration.rb#10
  def autoload_paths=(_arg0); end

  # source://railties//lib/rails/engine/configuration.rb#9
  def default_scope; end

  # source://railties//lib/rails/engine/configuration.rb#9
  def default_scope=(_arg0); end

  # source://railties//lib/rails/engine/configuration.rb#39
  def eager_load_paths; end

  # source://railties//lib/rails/engine/configuration.rb#10
  def eager_load_paths=(_arg0); end

  # source://railties//lib/rails/engine/configuration.rb#67
  def generators; end

  # source://railties//lib/rails/engine/configuration.rb#9
  def javascript_path; end

  # source://railties//lib/rails/engine/configuration.rb#9
  def javascript_path=(_arg0); end

  # source://railties//lib/rails/engine/configuration.rb#9
  def middleware; end

  # source://railties//lib/rails/engine/configuration.rb#9
  def middleware=(_arg0); end

  # source://railties//lib/rails/engine/configuration.rb#73
  def paths; end

  # source://railties//lib/rails/engine/configuration.rb#8
  def root; end

  # source://railties//lib/rails/engine/configuration.rb#115
  def root=(value); end

  # source://railties//lib/rails/engine/configuration.rb#9
  def route_set_class; end

  # source://railties//lib/rails/engine/configuration.rb#9
  def route_set_class=(_arg0); end
end

# source://railties//lib/rails/engine/lazy_route_set.rb#9
class Rails::Engine::LazyRouteSet < ::ActionDispatch::Routing::RouteSet
  # source://railties//lib/rails/engine/lazy_route_set.rb#49
  def initialize(config = T.unsafe(nil)); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#66
  def call(req); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#71
  def draw(&block); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#56
  def generate_extras(options, recall = T.unsafe(nil)); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#62
  def generate_url_helpers(supports_path); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#76
  def recognize_path(path, environment = T.unsafe(nil)); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#81
  def recognize_path_with_request(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#86
  def routes; end

  private

  # source://railties//lib/rails/engine/lazy_route_set.rb#92
  def method_missing_module; end
end

# source://railties//lib/rails/engine/lazy_route_set.rb#10
class Rails::Engine::LazyRouteSet::NamedRouteCollection < ::ActionDispatch::Routing::RouteSet::NamedRouteCollection
  # source://railties//lib/rails/engine/lazy_route_set.rb#11
  def route_defined?(name); end
end

# source://railties//lib/rails/engine/lazy_route_set.rb#17
module Rails::Engine::LazyRouteSet::ProxyUrlHelpers
  # source://railties//lib/rails/engine/lazy_route_set.rb#23
  def full_url_for(options); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#33
  def optimize_routes_generation?; end

  # source://railties//lib/rails/engine/lazy_route_set.rb#43
  def polymorphic_path(record_or_hash_or_array, options = T.unsafe(nil)); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#38
  def polymorphic_url(record_or_hash_or_array, options = T.unsafe(nil)); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#28
  def route_for(name, *args); end

  # source://railties//lib/rails/engine/lazy_route_set.rb#18
  def url_for(options); end
end

# source://railties//lib/rails/engine/railties.rb#5
class Rails::Engine::Railties
  include ::Enumerable

  # source://railties//lib/rails/engine/railties.rb#9
  def initialize; end

  # source://railties//lib/rails/engine/railties.rb#18
  def -(others); end

  # source://railties//lib/rails/engine/railties.rb#7
  def _all; end

  # source://railties//lib/rails/engine/railties.rb#14
  def each(*args, &block); end
end

# source://railties//lib/rails/health_controller.rb#35
class Rails::HealthController < ::ActionController::Base
  # source://railties//lib/rails/health_controller.rb#38
  def show; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  # source://railties//lib/rails/health_controller.rb#51
  def html_status(color:); end

  # source://railties//lib/rails/health_controller.rb#47
  def render_down; end

  # source://railties//lib/rails/health_controller.rb#43
  def render_up; end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_rescue_handlers; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_rescue_handlers=(new_value); end
  end
end

# source://railties//lib/rails/info.rb#9
module Rails::Info
  # source://railties//lib/rails/info.rb#10
  def properties; end

  # source://railties//lib/rails/info.rb#10
  def properties=(val); end

  class << self
    # source://railties//lib/rails/info.rb#31
    def inspect; end

    # source://railties//lib/rails/info.rb#10
    def properties; end

    # source://railties//lib/rails/info.rb#10
    def properties=(val); end

    # source://railties//lib/rails/info.rb#25
    def property(name, value = T.unsafe(nil)); end

    # source://railties//lib/rails/info.rb#43
    def to_html; end

    # source://railties//lib/rails/info.rb#31
    def to_s; end
  end
end

# source://railties//lib/rails/info_controller.rb#6
class Rails::InfoController < ::Rails::ApplicationController
  # source://railties//lib/rails/info_controller.rb#12
  def index; end

  # source://railties//lib/rails/info_controller.rb#35
  def notes; end

  # source://railties//lib/rails/info_controller.rb#16
  def properties; end

  # source://railties//lib/rails/info_controller.rb#21
  def routes; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  # source://railties//lib/rails/info_controller.rb#8
  def _layout_from_proc; end

  # source://railties//lib/rails/info_controller.rb#44
  def matching_routes(query:, exact_match:); end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout_conditions; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout_conditions=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

# source://railties//lib/rails/initializable.rb#6
module Rails::Initializable
  mixes_in_class_methods ::Rails::Initializable::ClassMethods

  # source://railties//lib/rails/initializable.rb#66
  def initializers; end

  # source://railties//lib/rails/initializable.rb#58
  def run_initializers(group = T.unsafe(nil), *args); end

  class << self
    # source://railties//lib/rails/initializable.rb#7
    def included(base); end
  end
end

# source://railties//lib/rails/initializable.rb#70
module Rails::Initializable::ClassMethods
  # source://railties//lib/rails/initializable.rb#88
  def initializer(name, opts = T.unsafe(nil), &blk); end

  # source://railties//lib/rails/initializable.rb#71
  def initializers; end

  # source://railties//lib/rails/initializable.rb#75
  def initializers_chain; end

  # source://railties//lib/rails/initializable.rb#84
  def initializers_for(binding); end
end

# source://railties//lib/rails/initializable.rb#45
class Rails::Initializable::Collection < ::Array
  include ::TSort

  # source://railties//lib/rails/initializable.rb#53
  def +(other); end

  # source://railties//lib/rails/initializable.rb#49
  def tsort_each_child(initializer, &block); end

  def tsort_each_node; end
end

# source://railties//lib/rails/initializable.rb#11
class Rails::Initializable::Initializer
  # source://railties//lib/rails/initializable.rb#14
  def initialize(name, context, options, &block); end

  # source://railties//lib/rails/initializable.rb#23
  def after; end

  # source://railties//lib/rails/initializable.rb#19
  def before; end

  # source://railties//lib/rails/initializable.rb#27
  def belongs_to?(group); end

  # source://railties//lib/rails/initializable.rb#35
  def bind(context); end

  # source://railties//lib/rails/initializable.rb#12
  def block; end

  # source://railties//lib/rails/initializable.rb#40
  def context_class; end

  # source://railties//lib/rails/initializable.rb#12
  def name; end

  # source://railties//lib/rails/initializable.rb#31
  def run(*args); end
end

# source://railties//lib/rails/test_unit/line_filtering.rb#6
module Rails::LineFiltering
  # source://railties//lib/rails/test_unit/line_filtering.rb#7
  def run(reporter, options = T.unsafe(nil)); end
end

# source://railties//lib/rails/mailers_controller.rb#6
class Rails::MailersController < ::Rails::ApplicationController
  # source://railties//lib/rails/mailers_controller.rb#22
  def download; end

  # source://railties//lib/rails/mailers_controller.rb#17
  def index; end

  # source://railties//lib/rails/mailers_controller.rb#32
  def preview; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  # source://railties//lib/rails/mailers_controller.rb#107
  def attachment_url(attachment); end

  # source://railties//lib/rails/mailers_controller.rb#101
  def attachments_for(email); end

  # source://railties//lib/rails/mailers_controller.rb#93
  def find_part(format); end

  # source://railties//lib/rails/mailers_controller.rb#81
  def find_preferred_part(*formats); end

  # source://railties//lib/rails/mailers_controller.rb#69
  def find_preview; end

  # source://railties//lib/rails/mailers_controller.rb#115
  def locale_query(locale); end

  # source://railties//lib/rails/mailers_controller.rb#111
  def part_query(mime_type); end

  # source://railties//lib/rails/mailers_controller.rb#119
  def set_locale(&block); end

  # source://railties//lib/rails/mailers_controller.rb#65
  def show_previews?; end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__helper_methods; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__helper_methods=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

# source://railties//lib/rails/mailers_controller.rb#0
module Rails::MailersController::HelperMethods
  include ::ActionText::ContentHelper
  include ::ActionText::TagHelper
  include ::InertiaRails::Helper
  include ::ViteRails::TagHelpers
  include ::ActionController::Base::HelperMethods

  # source://railties//lib/rails/mailers_controller.rb#13
  def attachment_url(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/mailers_controller.rb#13
  def locale_query(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/mailers_controller.rb#13
  def part_query(*_arg0, **_arg1, &_arg2); end
end

# source://railties//lib/rails/paths.rb#6
module Rails::Paths; end

# source://railties//lib/rails/paths.rb#114
class Rails::Paths::Path
  include ::Enumerable

  # source://railties//lib/rails/paths.rb#119
  def initialize(root, current, paths, options = T.unsafe(nil)); end

  # source://railties//lib/rails/paths.rb#171
  def <<(path); end

  # source://railties//lib/rails/paths.rb#132
  def absolute_current; end

  # source://railties//lib/rails/paths.rb#153
  def autoload!; end

  # source://railties//lib/rails/paths.rb#161
  def autoload?; end

  # source://railties//lib/rails/paths.rb#153
  def autoload_once!; end

  # source://railties//lib/rails/paths.rb#161
  def autoload_once?; end

  # source://railties//lib/rails/paths.rb#136
  def children; end

  # source://railties//lib/rails/paths.rb#176
  def concat(paths); end

  # source://railties//lib/rails/paths.rb#167
  def each(&block); end

  # source://railties//lib/rails/paths.rb#153
  def eager_load!; end

  # source://railties//lib/rails/paths.rb#161
  def eager_load?; end

  # source://railties//lib/rails/paths.rb#220
  def existent; end

  # source://railties//lib/rails/paths.rb#231
  def existent_directories; end

  # source://railties//lib/rails/paths.rb#201
  def expanded; end

  # source://railties//lib/rails/paths.rb#196
  def extensions; end

  # source://railties//lib/rails/paths.rb#143
  def first; end

  # source://railties//lib/rails/paths.rb#117
  def glob; end

  # source://railties//lib/rails/paths.rb#117
  def glob=(_arg0); end

  # source://railties//lib/rails/paths.rb#147
  def last; end

  # source://railties//lib/rails/paths.rb#153
  def load_path!; end

  # source://railties//lib/rails/paths.rb#161
  def load_path?; end

  # source://railties//lib/rails/paths.rb#188
  def paths; end

  # source://railties//lib/rails/paths.rb#171
  def push(path); end

  # source://railties//lib/rails/paths.rb#157
  def skip_autoload!; end

  # source://railties//lib/rails/paths.rb#157
  def skip_autoload_once!; end

  # source://railties//lib/rails/paths.rb#157
  def skip_eager_load!; end

  # source://railties//lib/rails/paths.rb#157
  def skip_load_path!; end

  # source://railties//lib/rails/paths.rb#201
  def to_a; end

  # source://railties//lib/rails/paths.rb#184
  def to_ary; end

  # source://railties//lib/rails/paths.rb#180
  def unshift(*paths); end

  private

  # source://railties//lib/rails/paths.rb#238
  def files_in(path); end
end

# source://railties//lib/rails/paths.rb#51
class Rails::Paths::Root
  # source://railties//lib/rails/paths.rb#54
  def initialize(path); end

  # source://railties//lib/rails/paths.rb#69
  def [](path); end

  # source://railties//lib/rails/paths.rb#59
  def []=(path, value); end

  # source://railties//lib/rails/paths.rb#64
  def add(path, options = T.unsafe(nil)); end

  # source://railties//lib/rails/paths.rb#85
  def all_paths; end

  # source://railties//lib/rails/paths.rb#89
  def autoload_once; end

  # source://railties//lib/rails/paths.rb#97
  def autoload_paths; end

  # source://railties//lib/rails/paths.rb#93
  def eager_load; end

  # source://railties//lib/rails/paths.rb#77
  def keys; end

  # source://railties//lib/rails/paths.rb#101
  def load_paths; end

  # source://railties//lib/rails/paths.rb#52
  def path; end

  # source://railties//lib/rails/paths.rb#52
  def path=(_arg0); end

  # source://railties//lib/rails/paths.rb#73
  def values; end

  # source://railties//lib/rails/paths.rb#81
  def values_at(*list); end

  private

  # source://railties//lib/rails/paths.rb#106
  def filter_by(&block); end
end

# source://railties//lib/rails/pwa_controller.rb#5
class Rails::PwaController < ::Rails::ApplicationController
  # source://railties//lib/rails/pwa_controller.rb#12
  def manifest; end

  # source://railties//lib/rails/pwa_controller.rb#8
  def service_worker; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end

# source://railties//lib/rails/rack.rb#4
module Rails::Rack; end

# source://railties//lib/rails/rack/logger.rb#14
class Rails::Rack::Logger < ::ActiveSupport::LogSubscriber
  # source://railties//lib/rails/rack/logger.rb#15
  def initialize(app, taggers = T.unsafe(nil)); end

  # source://railties//lib/rails/rack/logger.rb#20
  def call(env); end

  private

  # source://railties//lib/rails/rack/logger.rb#33
  def call_app(request, env); end

  # source://railties//lib/rails/rack/logger.rb#64
  def compute_tags(request); end

  # source://railties//lib/rails/rack/logger.rb#81
  def finish_request_instrumentation(handle, logger_tag_pop_count); end

  # source://railties//lib/rails/rack/logger.rb#77
  def logger; end

  # source://railties//lib/rails/rack/logger.rb#56
  def started_request_message(request); end
end

# source://railties//lib/rails/rack/silence_request.rb#19
class Rails::Rack::SilenceRequest
  # source://railties//lib/rails/rack/silence_request.rb#20
  def initialize(app, path:); end

  # source://railties//lib/rails/rack/silence_request.rb#24
  def call(env); end
end

# source://railties//lib/rails/railtie.rb#136
class Rails::Railtie
  include ::Rails::Initializable
  extend ::ActiveSupport::DescendantsTracker
  extend ::Rails::Initializable::ClassMethods

  # source://railties//lib/rails/railtie.rb#245
  def initialize; end

  # source://railties//lib/rails/railtie.rb#262
  def config; end

  # source://railties//lib/rails/railtie.rb#255
  def configure(&block); end

  # source://railties//lib/rails/railtie.rb#251
  def inspect; end

  # source://railties//lib/rails/railtie.rb#243
  def railtie_name(*_arg0, **_arg1, &_arg2); end

  # source://railties//lib/rails/railtie.rb#266
  def railtie_namespace; end

  protected

  # source://railties//lib/rails/railtie.rb#271
  def run_console_blocks(app); end

  # source://railties//lib/rails/railtie.rb#275
  def run_generators_blocks(app); end

  # source://railties//lib/rails/railtie.rb#279
  def run_runner_blocks(app); end

  # source://railties//lib/rails/railtie.rb#288
  def run_server_blocks(app); end

  # source://railties//lib/rails/railtie.rb#283
  def run_tasks_blocks(app); end

  private

  # source://railties//lib/rails/railtie.rb#294
  def each_registered_block(type, &block); end

  class << self
    # source://railties//lib/rails/railtie.rb#194
    def <=>(other); end

    # source://railties//lib/rails/railtie.rb#172
    def abstract_railtie?; end

    # source://railties//lib/rails/railtie.rb#146
    def config(*_arg0, **_arg1, &_arg2); end

    # source://railties//lib/rails/railtie.rb#190
    def configure(&block); end

    # source://railties//lib/rails/railtie.rb#156
    def console(&blk); end

    # source://railties//lib/rails/railtie.rb#164
    def generators(&blk); end

    # source://railties//lib/rails/railtie.rb#198
    def inherited(subclass); end

    # source://railties//lib/rails/railtie.rb#183
    def instance; end

    # source://railties//lib/rails/railtie.rb#176
    def railtie_name(name = T.unsafe(nil)); end

    # source://railties//lib/rails/railtie.rb#152
    def rake_tasks(&blk); end

    # source://railties//lib/rails/railtie.rb#160
    def runner(&blk); end

    # source://railties//lib/rails/railtie.rb#168
    def server(&blk); end

    # source://railties//lib/rails/railtie.rb#148
    def subclasses; end

    protected

    # source://railties//lib/rails/railtie.rb#206
    def increment_load_index; end

    # source://railties//lib/rails/railtie.rb#204
    def load_index; end

    private

    # source://railties//lib/rails/railtie.rb#212
    def generate_railtie_name(string); end

    # source://railties//lib/rails/railtie.rb#224
    def method_missing(name, *_arg1, **_arg2, &_arg3); end

    def new(*_arg0); end

    # source://railties//lib/rails/railtie.rb#235
    def register_block_for(type, &blk); end

    # source://railties//lib/rails/railtie.rb#216
    def respond_to_missing?(name, _); end
  end
end

# source://railties//lib/rails/railtie.rb#142
Rails::Railtie::ABSTRACT_RAILTIES = T.let(T.unsafe(nil), Array)

# source://railties//lib/rails/railtie/configuration.rb#7
class Rails::Railtie::Configuration
  # source://railties//lib/rails/railtie/configuration.rb#8
  def initialize; end

  # source://railties//lib/rails/railtie/configuration.rb#70
  def after_initialize(&block); end

  # source://railties//lib/rails/railtie/configuration.rb#75
  def after_routes_loaded(&block); end

  # source://railties//lib/rails/railtie/configuration.rb#47
  def app_generators; end

  # source://railties//lib/rails/railtie/configuration.rb#39
  def app_middleware; end

  # source://railties//lib/rails/railtie/configuration.rb#54
  def before_configuration(&block); end

  # source://railties//lib/rails/railtie/configuration.rb#60
  def before_eager_load(&block); end

  # source://railties//lib/rails/railtie/configuration.rb#65
  def before_initialize(&block); end

  # source://railties//lib/rails/railtie/configuration.rb#18
  def eager_load_namespaces; end

  # source://railties//lib/rails/railtie/configuration.rb#90
  def respond_to?(name, include_private = T.unsafe(nil)); end

  # source://railties//lib/rails/railtie/configuration.rb#86
  def to_prepare(&blk); end

  # source://railties//lib/rails/railtie/configuration.rb#80
  def to_prepare_blocks; end

  # source://railties//lib/rails/railtie/configuration.rb#30
  def watchable_dirs; end

  # source://railties//lib/rails/railtie/configuration.rb#23
  def watchable_files; end

  private

  # source://railties//lib/rails/railtie/configuration.rb#95
  def actual_method?(key); end

  # source://railties//lib/rails/railtie/configuration.rb#99
  def method_missing(name, *args, &blk); end

  class << self
    # source://railties//lib/rails/railtie/configuration.rb#13
    def eager_load_namespaces; end
  end
end

# source://railties//lib/rails/source_annotation_extractor.rb#21
class Rails::SourceAnnotationExtractor
  # source://railties//lib/rails/source_annotation_extractor.rb#154
  def initialize(tag); end

  # source://railties//lib/rails/source_annotation_extractor.rb#203
  def display(results, options = T.unsafe(nil)); end

  # source://railties//lib/rails/source_annotation_extractor.rb#160
  def find(dirs); end

  # source://railties//lib/rails/source_annotation_extractor.rb#168
  def find_in(dir); end

  # source://railties//lib/rails/source_annotation_extractor.rb#152
  def tag; end

  class << self
    # source://railties//lib/rails/source_annotation_extractor.rb#145
    def enumerate(tag = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

# source://railties//lib/rails/source_annotation_extractor.rb#71
class Rails::SourceAnnotationExtractor::Annotation < ::Struct
  # source://railties//lib/rails/source_annotation_extractor.rb#124
  def to_s(options = T.unsafe(nil)); end

  class << self
    # source://railties//lib/rails/source_annotation_extractor.rb#72
    def directories; end

    # source://railties//lib/rails/source_annotation_extractor.rb#92
    def extensions; end

    # source://railties//lib/rails/source_annotation_extractor.rb#78
    def register_directories(*dirs); end

    # source://railties//lib/rails/source_annotation_extractor.rb#98
    def register_extensions(*exts, &block); end

    # source://railties//lib/rails/source_annotation_extractor.rb#88
    def register_tags(*additional_tags); end

    # source://railties//lib/rails/source_annotation_extractor.rb#82
    def tags; end
  end
end

# source://railties//lib/rails/source_annotation_extractor.rb#24
class Rails::SourceAnnotationExtractor::ParserExtractor < ::Struct
  # source://railties//lib/rails/source_annotation_extractor.rb#26
  def annotations(file); end
end

# source://railties//lib/rails/source_annotation_extractor.rb#59
class Rails::SourceAnnotationExtractor::PatternExtractor < ::Struct
  # source://railties//lib/rails/source_annotation_extractor.rb#60
  def annotations(file); end
end

# source://railties//lib/rails/test_unit/test_parser.rb#12
module Rails::TestUnit; end

# source://railties//lib/rails/test_unit/runner.rb#151
class Rails::TestUnit::CompositeFilter
  # source://railties//lib/rails/test_unit/runner.rb#154
  def initialize(runnable, filter, patterns); end

  # source://railties//lib/rails/test_unit/runner.rb#161
  def ===(method); end

  # source://railties//lib/rails/test_unit/runner.rb#152
  def named_filter; end

  private

  # source://railties//lib/rails/test_unit/runner.rb#176
  def derive_line_filters(patterns); end

  # source://railties//lib/rails/test_unit/runner.rb#166
  def derive_named_filter(filter); end
end

# source://railties//lib/rails/test_unit/runner.rb#187
class Rails::TestUnit::Filter
  # source://railties//lib/rails/test_unit/runner.rb#188
  def initialize(runnable, file, line_or_range); end

  # source://railties//lib/rails/test_unit/runner.rb#197
  def ===(method); end

  private

  # source://railties//lib/rails/test_unit/runner.rb#209
  def definition_for(method); end
end

# source://railties//lib/rails/test_unit/runner.rb#12
class Rails::TestUnit::InvalidTestError < ::ArgumentError
  # source://railties//lib/rails/test_unit/runner.rb#13
  def initialize(path, suggestion); end

  # source://railties//lib/rails/test_unit/runner.rb#20
  def backtrace(*args); end
end

# source://railties//lib/rails/test_unit/runner.rb#25
class Rails::TestUnit::Runner
  # source://railties//lib/rails/test_unit/runner.rb#28
  def filters; end

  class << self
    # source://railties//lib/rails/test_unit/runner.rb#31
    def attach_before_load_options(opts); end

    # source://railties//lib/rails/test_unit/runner.rb#82
    def compose_filter(runnable, filter); end

    # source://railties//lib/rails/test_unit/runner.rb#28
    def filters; end

    # source://railties//lib/rails/test_unit/runner.rb#61
    def load_tests(argv); end

    # source://railties//lib/rails/test_unit/runner.rb#36
    def parse_options(argv); end

    # source://railties//lib/rails/test_unit/runner.rb#55
    def run(argv = T.unsafe(nil)); end

    # source://railties//lib/rails/test_unit/runner.rb#49
    def run_from_rake(test_command, argv = T.unsafe(nil)); end

    private

    # source://railties//lib/rails/test_unit/runner.rb#117
    def default_test_exclude_glob; end

    # source://railties//lib/rails/test_unit/runner.rb#113
    def default_test_glob; end

    # source://railties//lib/rails/test_unit/runner.rb#93
    def extract_filters(argv); end

    # source://railties//lib/rails/test_unit/runner.rb#129
    def list_tests(patterns); end

    # source://railties//lib/rails/test_unit/runner.rb#136
    def normalize_declarative_test_filter(filter); end

    # source://railties//lib/rails/test_unit/runner.rb#125
    def path_argument?(arg); end

    # source://railties//lib/rails/test_unit/runner.rb#121
    def regexp_filter?(arg); end
  end
end

# source://railties//lib/rails/test_unit/runner.rb#27
Rails::TestUnit::Runner::PATH_ARGUMENT_PATTERN = T.let(T.unsafe(nil), Regexp)

# source://railties//lib/rails/test_unit/runner.rb#26
Rails::TestUnit::Runner::TEST_FOLDERS = T.let(T.unsafe(nil), Array)

# source://railties//lib/rails/test_unit/test_parser.rb#15
module Rails::TestUnit::TestParser
  class << self
    # source://railties//lib/rails/test_unit/test_parser.rb#19
    def definition_for(method); end

    # source://railties//lib/rails/test_unit/test_parser.rb#27
    def ranges(filepath); end
  end
end

# source://railties//lib/rails/test_unit/railtie.rb#6
class Rails::TestUnitRailtie < ::Rails::Railtie; end

# source://railties//lib/rails/gem_version.rb#9
module Rails::VERSION; end

# source://railties//lib/rails/gem_version.rb#10
Rails::VERSION::MAJOR = T.let(T.unsafe(nil), Integer)

# source://railties//lib/rails/gem_version.rb#11
Rails::VERSION::MINOR = T.let(T.unsafe(nil), Integer)

# source://railties//lib/rails/gem_version.rb#13
Rails::VERSION::PRE = T.let(T.unsafe(nil), T.untyped)

# source://railties//lib/rails/gem_version.rb#15
Rails::VERSION::STRING = T.let(T.unsafe(nil), String)

# source://railties//lib/rails/gem_version.rb#12
Rails::VERSION::TINY = T.let(T.unsafe(nil), Integer)

# source://railties//lib/rails/welcome_controller.rb#5
class Rails::WelcomeController < ::Rails::ApplicationController
  # source://railties//lib/rails/welcome_controller.rb#9
  def index; end

  private

  # source://actionview/8.0.2/lib/action_view/layouts.rb#328
  def _layout(lookup_context, formats, keys); end

  class << self
    private

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr___callbacks; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr___callbacks=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr__layout_conditions; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr__layout_conditions=(new_value); end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#15
    def __class_attr_middleware_stack; end

    # source://activesupport/8.0.2/lib/active_support/class_attribute.rb#17
    def __class_attr_middleware_stack=(new_value); end
  end
end
