# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `vite_ruby` gem.
# Please instead update this file by running `bin/tapioca gem vite_ruby`.


# source://vite_ruby//lib/vite_ruby.rb#18
class ViteRuby
  # source://vite_ruby//lib/vite_ruby.rb#70
  def initialize(**config_options); end

  # source://vite_ruby//lib/vite_ruby.rb#122
  def builder; end

  # source://vite_ruby//lib/vite_ruby.rb#127
  def commands; end

  # source://vite_ruby//lib/vite_ruby.rb#132
  def config; end

  # source://vite_ruby//lib/vite_ruby.rb#142
  def configure(**options); end

  # source://vite_ruby//lib/vite_ruby.rb#86
  def dev_server_running?; end

  # source://vite_ruby//lib/vite_ruby.rb#80
  def digest; end

  # source://vite_ruby//lib/vite_ruby.rb#104
  def env; end

  # source://vite_ruby//lib/vite_ruby.rb#74
  def logger; end

  # source://vite_ruby//lib/vite_ruby.rb#68
  def logger=(_arg0); end

  # source://vite_ruby//lib/vite_ruby.rb#147
  def manifest; end

  # source://vite_ruby//lib/vite_ruby.rb#117
  def run(argv, **options); end

  # source://vite_ruby//lib/vite_ruby.rb#109
  def run_proxy?; end

  class << self
    # source://vite_ruby//lib/vite_ruby.rb#43
    def bootstrap; end

    # source://forwardable/1.3.3/forwardable.rb#231
    def commands(*args, **_arg1, &block); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def config(*args, **_arg1, &block); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def configure(*args, **_arg1, &block); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def digest(*args, **_arg1, &block); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def env(*args, **_arg1, &block); end

    # source://vite_ruby//lib/vite_ruby.rb#59
    def framework_libraries; end

    # source://vite_ruby//lib/vite_ruby.rb#48
    def install_tasks; end

    # source://vite_ruby//lib/vite_ruby.rb#38
    def instance; end

    # source://forwardable/1.3.3/forwardable.rb#231
    def mode(*args, **_arg1, &block); end

    # source://vite_ruby//lib/vite_ruby.rb#53
    def reload_with(**config_options); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def run(*args, **_arg1, &block); end

    # source://forwardable/1.3.3/forwardable.rb#231
    def run_proxy?(*args, **_arg1, &block); end
  end
end

# source://vite_ruby//lib/vite_ruby/build.rb#7
class ViteRuby::Build < ::Struct
  def current_digest; end
  def current_digest=(_); end
  def digest; end
  def digest=(_); end
  def errors; end
  def errors=(_); end

  # source://vite_ruby//lib/vite_ruby/build.rb#43
  def fresh?; end

  def last_build_path; end
  def last_build_path=(_); end

  # source://vite_ruby//lib/vite_ruby/build.rb#49
  def retry_failed?; end

  # source://vite_ruby//lib/vite_ruby/build.rb#37
  def stale?; end

  def success; end
  def success=(_); end
  def timestamp; end
  def timestamp=(_); end

  # source://vite_ruby//lib/vite_ruby/build.rb#73
  def to_json(*_args); end

  def vite_ruby; end
  def vite_ruby=(_); end

  # source://vite_ruby//lib/vite_ruby/build.rb#56
  def with_result(**attrs); end

  # source://vite_ruby//lib/vite_ruby/build.rb#68
  def write_to_cache; end

  class << self
    def [](*_arg0); end

    # source://vite_ruby//lib/vite_ruby/build.rb#10
    def from_previous(last_build_path, current_digest); end

    def inspect; end
    def keyword_init?; end
    def members; end
    def new(*_arg0); end

    private

    # source://vite_ruby//lib/vite_ruby/build.rb#30
    def default_metadata; end

    # source://vite_ruby//lib/vite_ruby/build.rb#21
    def parse_metadata(pathname); end
  end
end

# source://vite_ruby//lib/vite_ruby/builder.rb#6
class ViteRuby::Builder
  extend ::Forwardable

  # source://vite_ruby//lib/vite_ruby/builder.rb#7
  def initialize(vite_ruby); end

  # source://vite_ruby//lib/vite_ruby/builder.rb#13
  def build(*args); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def config(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/builder.rb#31
  def last_build_metadata(ssr: T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def logger(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def run(*args, **_arg1, &block); end

  private

  # source://vite_ruby//lib/vite_ruby/builder.rb#66
  def build_with_vite(*args); end

  # source://vite_ruby//lib/vite_ruby/builder.rb#48
  def last_build_path(ssr:); end

  # source://vite_ruby//lib/vite_ruby/builder.rb#75
  def log_build_result(_stdout, stderr, status); end

  # source://vite_ruby//lib/vite_ruby/builder.rb#42
  def record_build_metadata(build, **attrs); end

  # source://vite_ruby//lib/vite_ruby/builder.rb#54
  def watched_files_digest; end
end

# source://vite_ruby//lib/vite_ruby/cli.rb#7
class ViteRuby::CLI
  extend ::Dry::CLI::Registry

  class << self
    # source://vite_ruby//lib/vite_ruby/cli.rb#20
    def require_framework_libraries(path = T.unsafe(nil)); end
  end
end

# source://vite_ruby//lib/vite_ruby/cli/build.rb#3
class ViteRuby::CLI::Build < ::ViteRuby::CLI::Vite
  # source://vite_rails/3.0.19/lib/vite_rails/cli.rb#9
  def call(**options); end
end

# source://vite_ruby//lib/vite_ruby/cli/build.rb#4
ViteRuby::CLI::Build::DEFAULT_ENV = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/cli/clobber.rb#3
class ViteRuby::CLI::Clobber < ::Dry::CLI::Command
  extend ::Dry::CLI::Command::ClassMethods

  # source://vite_ruby//lib/vite_ruby/cli/clobber.rb#10
  def call(mode:, **_arg1); end
end

# source://vite_ruby//lib/vite_ruby/cli/dev.rb#3
class ViteRuby::CLI::Dev < ::ViteRuby::CLI::Vite
  # source://vite_ruby//lib/vite_ruby/cli/dev.rb#10
  def call(**options); end
end

# source://vite_ruby//lib/vite_ruby/cli/dev.rb#4
ViteRuby::CLI::Dev::DEFAULT_ENV = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#8
module ViteRuby::CLI::FileUtils
  class << self
    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#34
    def append(path, contents); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#25
    def cp(source, destination); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#67
    def inject_line_after(path, target, contents); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#75
    def inject_line_after_last(path, target, contents); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#59
    def inject_line_before(path, target, contents); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#48
    def replace_first_line(path, target, replacement); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#14
    def write(path, *content); end

    private

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#122
    def _inject_line_after(path, target, contents, finder); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#110
    def _inject_line_before(path, target, contents, finder); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#96
    def index(content, path, target); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#85
    def mkdir_p(path); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#90
    def read_lines(path); end

    # source://vite_ruby//lib/vite_ruby/cli/file_utils.rb#103
    def rindex(content, path, target); end
  end
end

# source://vite_ruby//lib/vite_ruby/cli/install.rb#6
class ViteRuby::CLI::Install < ::Dry::CLI::Command
  extend ::Dry::CLI::Command::ClassMethods

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#11
  def call(package_manager: T.unsafe(nil), **_arg1); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def config(*args, **_arg1, &block); end

  # source://vite_rails/3.0.19/lib/vite_rails/cli.rb#60
  def install_sample_files; end

  # source://vite_rails/3.0.19/lib/vite_rails/cli.rb#28
  def setup_app_files; end

  protected

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#37
  def js_dependencies; end

  private

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def append(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#72
  def copy_template(path, to:); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def cp(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#77
  def create_configuration_files; end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def inject_line_after(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def inject_line_after_last(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def inject_line_before(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#104
  def install_gitignore; end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#85
  def install_js_dependencies; end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#134
  def install_js_packages(deps); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def replace_first_line(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#119
  def root; end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#127
  def run_with_capture(*args, **options); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#123
  def say(*args); end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#139
  def silent_warnings; end

  # source://vite_ruby//lib/vite_ruby/cli/install.rb#65
  def write(*args); end
end

# source://vite_ruby//lib/vite_ruby/cli/install.rb#70
ViteRuby::CLI::Install::TEMPLATES_PATH = T.let(T.unsafe(nil), Pathname)

# source://vite_ruby//lib/vite_ruby/cli/ssr.rb#3
class ViteRuby::CLI::SSR < ::ViteRuby::CLI::Vite
  # source://vite_ruby//lib/vite_ruby/cli/ssr.rb#10
  def call(mode:, inspect: T.unsafe(nil), trace_deprecation: T.unsafe(nil)); end
end

# source://vite_ruby//lib/vite_ruby/cli/ssr.rb#4
ViteRuby::CLI::SSR::DEFAULT_ENV = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/cli/ssr.rb#5
ViteRuby::CLI::SSR::JS_EXTENSIONS = T.let(T.unsafe(nil), Array)

# source://vite_ruby//lib/vite_ruby/cli/upgrade.rb#3
class ViteRuby::CLI::Upgrade < ::ViteRuby::CLI::Install
  # source://vite_ruby//lib/vite_ruby/cli/upgrade.rb#6
  def call(**_arg0); end

  protected

  # source://vite_ruby//lib/vite_ruby/cli/upgrade.rb#22
  def upgrade_npm_packages; end

  # source://vite_ruby//lib/vite_ruby/cli/upgrade.rb#13
  def upgrade_ruby_gems; end
end

# source://vite_ruby//lib/vite_ruby/cli/upgrade_packages.rb#3
class ViteRuby::CLI::UpgradePackages < ::ViteRuby::CLI::Install
  # source://vite_ruby//lib/vite_ruby/cli/upgrade_packages.rb#6
  def call(**_arg0); end
end

# source://vite_ruby//lib/vite_ruby/cli/version.rb#3
class ViteRuby::CLI::Version < ::Dry::CLI::Command
  extend ::Dry::CLI::Command::ClassMethods

  # source://vite_ruby//lib/vite_ruby/cli/version.rb#6
  def call(**_arg0); end
end

# source://vite_ruby//lib/vite_ruby/cli/vite.rb#3
class ViteRuby::CLI::Vite < ::Dry::CLI::Command
  extend ::Dry::CLI::Command::ClassMethods

  # source://vite_ruby//lib/vite_ruby/cli/vite.rb#19
  def call(mode:, args: T.unsafe(nil), clobber: T.unsafe(nil), node_options: T.unsafe(nil), inspect: T.unsafe(nil), trace_deprecation: T.unsafe(nil), **boolean_opts); end

  class << self
    # source://vite_ruby//lib/vite_ruby/cli/vite.rb#6
    def executable_options; end

    # source://vite_ruby//lib/vite_ruby/cli/vite.rb#13
    def shared_options; end
  end
end

# source://vite_ruby//lib/vite_ruby/cli/vite.rb#4
ViteRuby::CLI::Vite::CURRENT_ENV = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby.rb#23
ViteRuby::COMPANION_LIBRARIES = T.let(T.unsafe(nil), Hash)

# source://vite_ruby//lib/vite_ruby/commands.rb#5
class ViteRuby::Commands
  extend ::Forwardable

  # source://vite_ruby//lib/vite_ruby/commands.rb#6
  def initialize(vite_ruby); end

  # source://vite_ruby//lib/vite_ruby/commands.rb#20
  def build(*args); end

  # source://vite_ruby//lib/vite_ruby/commands.rb#11
  def build_from_task(*args); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def builder(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/commands.rb#25
  def clobber; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def config(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/commands.rb#32
  def install_binstubs; end

  # source://vite_ruby//lib/vite_ruby/commands.rb#38
  def legacy_npm_version?; end

  # source://vite_ruby//lib/vite_ruby/commands.rb#43
  def legacy_yarn_version?; end

  # source://forwardable/1.3.3/forwardable.rb#231
  def logger(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def logger=(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def manifest(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/commands.rb#70
  def print_info; end

  # source://vite_ruby//lib/vite_ruby/commands.rb#48
  def verify_install; end

  private

  # source://vite_ruby//lib/vite_ruby/commands.rb#109
  def ensure_log_goes_to_stdout; end

  # source://vite_ruby//lib/vite_ruby/commands.rb#101
  def with_node_env(env); end
end

# source://vite_ruby//lib/vite_ruby/compatibility_check.rb#10
module ViteRuby::CompatibilityCheck
  class << self
    # source://vite_ruby//lib/vite_ruby/compatibility_check.rb#38
    def compatible_plugin?(npm_req, ruby_req); end

    # source://vite_ruby//lib/vite_ruby/compatibility_check.rb#22
    def raise_unless_satisfied(npm_req, ruby_req); end

    # source://vite_ruby//lib/vite_ruby/compatibility_check.rb#13
    def verify_plugin_version(root); end
  end
end

# source://vite_ruby//lib/vite_ruby/config.rb#7
class ViteRuby::Config
  extend ::ViteRails::Config

  # source://vite_ruby//lib/vite_ruby/config.rb#117
  def initialize(attrs); end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def additional_entrypoints; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def asset_host; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def assets_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def auto_build; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def base; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def build_cache_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#37
  def build_output_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def config_path; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def dev_server_connect_timeout; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def entrypoints_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def hide_build_console_output; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def host; end

  # source://vite_ruby//lib/vite_ruby/config.rb#16
  def host_with_port; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def https; end

  # source://vite_ruby//lib/vite_ruby/config.rb#21
  def known_manifest_paths; end

  # source://vite_ruby//lib/vite_ruby/config.rb#57
  def load_ruby_config; end

  # source://vite_ruby//lib/vite_ruby/config.rb#32
  def manifest_paths; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def mode; end

  # source://vite_ruby//lib/vite_ruby/config.rb#8
  def origin; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def package_manager; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def port; end

  # source://vite_ruby//lib/vite_ruby/config.rb#12
  def protocol; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def public_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def public_output_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#42
  def resolved_entrypoints_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def root; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def skip_compatibility_check; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def skip_proxy; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def source_code_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def ssr_build_enabled; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def ssr_entrypoint; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def ssr_output_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#63
  def to_env(env_vars = T.unsafe(nil)); end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def vite_bin_path; end

  # source://vite_ruby//lib/vite_ruby/config.rb#47
  def vite_cache_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#52
  def vite_root_dir; end

  # source://vite_ruby//lib/vite_ruby/config.rb#217
  def watch_additional_paths; end

  # source://vite_ruby//lib/vite_ruby/config.rb#72
  def watched_paths; end

  # source://vite_ruby//lib/vite_ruby/config.rb#84
  def within_root(&block); end

  private

  # source://vite_ruby//lib/vite_ruby/config.rb#103
  def coerce_booleans(config, *names); end

  # source://vite_ruby//lib/vite_ruby/config.rb#92
  def coerce_values(config); end

  # source://vite_ruby//lib/vite_ruby/config.rb#108
  def detect_package_manager(root); end

  class << self
    # source://vite_ruby//lib/vite_ruby/config.rb#126
    def resolve_config(**attrs); end

    private

    # source://vite_rails/3.0.19/lib/vite_rails/config.rb#7
    def config_defaults; end

    # source://vite_ruby//lib/vite_ruby/config.rb#169
    def config_from_env; end

    # source://vite_ruby//lib/vite_ruby/config.rb#178
    def config_from_file(path, mode:); end

    # source://vite_ruby//lib/vite_ruby/config.rb#155
    def load_json(path); end

    def new(*_arg0); end

    # source://vite_ruby//lib/vite_ruby/config.rb#164
    def option_from_env(name); end
  end
end

# source://vite_ruby//lib/vite_ruby/config.rb#195
ViteRuby::Config::CONFIGURABLE_WITH_ENV = T.let(T.unsafe(nil), Array)

# source://vite_ruby//lib/vite_ruby/config.rb#189
ViteRuby::Config::DEFAULT_CONFIG = T.let(T.unsafe(nil), Hash)

# source://vite_ruby//lib/vite_ruby/config.rb#198
ViteRuby::Config::DEFAULT_WATCHED_PATHS = T.let(T.unsafe(nil), Array)

# source://vite_ruby//lib/vite_ruby/config.rb#192
ViteRuby::Config::NOT_CONFIGURABLE_WITH_ENV = T.let(T.unsafe(nil), Array)

# source://vite_ruby//lib/vite_ruby/version.rb#8
ViteRuby::DEFAULT_PLUGIN_VERSION = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/version.rb#7
ViteRuby::DEFAULT_VITE_VERSION = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#6
class ViteRuby::DevServerProxy < ::Rack::Proxy
  extend ::Forwardable

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#10
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def config(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def dev_server_running?(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#17
  def perform_request(env); end

  private

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#64
  def file_in_vite_root?(path); end

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#44
  def forward_to_vite_dev_server(env); end

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#37
  def normalize_uri(uri); end

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#32
  def rewrite_uri_for_vite(env); end

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#55
  def vite_should_handle?(env); end

  # source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#73
  def vite_url_prefix; end
end

# source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#7
ViteRuby::DevServerProxy::HOST_WITH_PORT_REGEX = T.let(T.unsafe(nil), Regexp)

# source://vite_ruby//lib/vite_ruby/dev_server_proxy.rb#8
ViteRuby::DevServerProxy::VITE_DEPENDENCY_PREFIX = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby.rb#20
ViteRuby::ENV_PREFIX = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/error.rb#4
class ViteRuby::Error < ::StandardError
  # source://vite_ruby//lib/vite_ruby/error.rb#5
  def message; end
end

# source://vite_ruby//lib/vite_ruby/io.rb#6
module ViteRuby::IO
  class << self
    # source://vite_ruby//lib/vite_ruby/io.rb#10
    def capture(*cmd, with_output: T.unsafe(nil), stdin_data: T.unsafe(nil), **opts); end

    # source://vite_ruby//lib/vite_ruby/io.rb#23
    def read_lines(io); end
  end
end

# source://vite_ruby//lib/vite_ruby/manifest.rb#12
class ViteRuby::Manifest
  extend ::Forwardable

  # source://vite_ruby//lib/vite_ruby/manifest.rb#13
  def initialize(vite_ruby); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def builder(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def config(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def dev_server_running?(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#21
  def path_for(name, **options); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#61
  def react_preamble_code; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#50
  def react_refresh_preamble; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#40
  def refresh; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#27
  def resolve_entries(*names, **options); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#45
  def vite_client_src; end

  protected

  # source://vite_ruby//lib/vite_ruby/manifest.rb#89
  def lookup(name, **options); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#78
  def lookup!(name, **options); end

  private

  # source://vite_ruby//lib/vite_ruby/manifest.rb#206
  def extension_for_type(entry_type); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#111
  def find_manifest_entry(name); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#130
  def load_manifest; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#123
  def manifest; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#216
  def missing_entry_error(name, **options); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#144
  def prefix_asset_with_host(path); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#138
  def prefix_vite_asset(path); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#183
  def resolve_absolute_entry(name); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#165
  def resolve_entry_name(name, type: T.unsafe(nil)); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#154
  def resolve_references(manifest); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#192
  def resolve_virtual_entry(name); end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#106
  def should_build?; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#149
  def vite_asset_origin; end

  # source://vite_ruby//lib/vite_ruby/manifest.rb#197
  def with_file_extension(name, entry_type); end
end

# source://vite_ruby//lib/vite_ruby/manifest.rb#98
ViteRuby::Manifest::FS_PREFIX = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#7
class ViteRuby::MissingEntrypointError < ::ViteRuby::Error
  # source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#10
  def initialize(file_name:, last_build:, manifest:, config:); end

  # source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#8
  def config; end

  # source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#8
  def file_name; end

  # source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#8
  def last_build; end

  # source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#8
  def manifest; end

  # source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#24
  def possible_causes(last_build); end
end

# source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#43
ViteRuby::MissingEntrypointError::DEFAULT_CAUSES = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#36
ViteRuby::MissingEntrypointError::FAILED_BUILD_CAUSES = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/missing_entrypoint_error.rb#49
ViteRuby::MissingEntrypointError::NO_AUTO_BUILD_CAUSES = T.let(T.unsafe(nil), String)

# source://vite_ruby//lib/vite_ruby/missing_executable_error.rb#4
class ViteRuby::MissingExecutableError < ::ViteRuby::Error
  # source://vite_ruby//lib/vite_ruby/missing_executable_error.rb#5
  def initialize(error = T.unsafe(nil)); end
end

# source://vite_ruby//lib/vite_ruby/runner.rb#4
class ViteRuby::Runner
  extend ::Forwardable

  # source://vite_ruby//lib/vite_ruby/runner.rb#5
  def initialize(vite_ruby); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def config(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def env(*args, **_arg1, &block); end

  # source://forwardable/1.3.3/forwardable.rb#231
  def logger(*args, **_arg1, &block); end

  # source://vite_ruby//lib/vite_ruby/runner.rb#10
  def run(argv, exec: T.unsafe(nil)); end

  private

  # source://vite_ruby//lib/vite_ruby/runner.rb#29
  def command_for(args); end

  # source://vite_ruby//lib/vite_ruby/runner.rb#39
  def vite_executable(*exec_args); end
end

# source://vite_ruby//lib/vite_ruby/version.rb#4
ViteRuby::VERSION = T.let(T.unsafe(nil), String)
